--
-- PostgreSQL database dump
--

\restrict WL0AnVSf5pPg7KC8guvzi0C03DywOr8jYVhluDHg69OPPM8oXI35e2xnKwarB0T

-- Dumped from database version 16.11 (Ubuntu 16.11-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.11 (Ubuntu 16.11-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO postgres;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO postgres;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO postgres;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_channelanalysis; Type: TABLE; Schema: public; Owner: us
--

CREATE TABLE public.core_channelanalysis (
    id bigint NOT NULL,
    channel_url character varying(255) NOT NULL,
    channel_type character varying(50) NOT NULL,
    task_id character varying(255) NOT NULL,
    status character varying(20) NOT NULL,
    progress integer NOT NULL,
    result jsonb NOT NULL,
    error text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    client_id bigint NOT NULL,
    CONSTRAINT core_channelanalysis_progress_check CHECK ((progress >= 0))
);


ALTER TABLE public.core_channelanalysis OWNER TO us;

--
-- Name: core_channelanalysis_id_seq; Type: SEQUENCE; Schema: public; Owner: us
--

ALTER TABLE public.core_channelanalysis ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_channelanalysis_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_client; Type: TABLE; Schema: public; Owner: us
--

CREATE TABLE public.core_client (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    slug character varying(50) NOT NULL,
    timezone character varying(64) NOT NULL,
    telegram_api_hash character varying(255) NOT NULL,
    telegram_api_id character varying(255) NOT NULL,
    telegram_source_channels text NOT NULL,
    instagram_access_token text NOT NULL,
    instagram_source_accounts text NOT NULL,
    rss_source_feeds text NOT NULL,
    youtube_api_key character varying(255) NOT NULL,
    youtube_source_channels text NOT NULL,
    vkontakte_access_token text NOT NULL,
    vkontakte_source_groups text NOT NULL,
    avatar text NOT NULL,
    desires text NOT NULL,
    objections text NOT NULL,
    pains text NOT NULL,
    telegram_client_channel character varying(255) NOT NULL,
    ai_analysis_channel_type character varying(50) NOT NULL,
    ai_analysis_channel_url character varying(255) NOT NULL,
    expert_books text NOT NULL,
    video_prompt text NOT NULL,
    add_video_prompt text NOT NULL,
    base_video_prompt text NOT NULL,
    last_image_generation_at timestamp with time zone,
    last_video_generation_at timestamp with time zone,
    brand_name character varying(255) NOT NULL
);


ALTER TABLE public.core_client OWNER TO us;

--
-- Name: core_client_id_seq; Type: SEQUENCE; Schema: public; Owner: us
--

ALTER TABLE public.core_client ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_client_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_connection; Type: TABLE; Schema: public; Owner: us
--

CREATE TABLE public.core_connection (
    id bigint NOT NULL,
    provider character varying(30) NOT NULL,
    name character varying(255) NOT NULL,
    provider_user_id character varying(255) NOT NULL,
    account_id character varying(255) NOT NULL,
    access_token text NOT NULL,
    refresh_token text NOT NULL,
    expires_at timestamp with time zone,
    scopes jsonb NOT NULL,
    status character varying(20) NOT NULL,
    metadata jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    last_error text NOT NULL,
    client_id bigint NOT NULL,
    created_by_id integer
);


ALTER TABLE public.core_connection OWNER TO us;

--
-- Name: core_connection_id_seq; Type: SEQUENCE; Schema: public; Owner: us
--

ALTER TABLE public.core_connection ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_connection_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_contenttemplate; Type: TABLE; Schema: public; Owner: us
--

CREATE TABLE public.core_contenttemplate (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    tone character varying(50) NOT NULL,
    length integer NOT NULL,
    language character varying(5) NOT NULL,
    additional_instructions text NOT NULL,
    is_default boolean NOT NULL,
    include_hashtags boolean NOT NULL,
    max_hashtags integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    client_id bigint NOT NULL,
    type character varying(50) NOT NULL,
    seo_prompt_template text NOT NULL,
    trend_prompt_template text NOT NULL,
    CONSTRAINT core_contenttemplate_length_90dd1fd6_check CHECK ((length >= 0))
);


ALTER TABLE public.core_contenttemplate OWNER TO us;

--
-- Name: core_contenttemplate_id_seq; Type: SEQUENCE; Schema: public; Owner: us
--

ALTER TABLE public.core_contenttemplate ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_contenttemplate_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_post; Type: TABLE; Schema: public; Owner: us
--

CREATE TABLE public.core_post (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    text text NOT NULL,
    status character varying(20) NOT NULL,
    tags jsonb NOT NULL,
    source_links jsonb NOT NULL,
    generated_by character varying(50) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    client_id bigint NOT NULL,
    created_by_id integer,
    publish_image boolean NOT NULL,
    publish_text boolean NOT NULL,
    publish_video boolean NOT NULL,
    episode_number integer,
    regeneration_count integer NOT NULL,
    story_id bigint,
    template_id bigint,
    hook_title character varying(100) NOT NULL,
    wordstat_phrases_used jsonb NOT NULL
);


ALTER TABLE public.core_post OWNER TO us;

--
-- Name: core_post_id_seq; Type: SEQUENCE; Schema: public; Owner: us
--

ALTER TABLE public.core_post ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_post_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_postimage; Type: TABLE; Schema: public; Owner: us
--

CREATE TABLE public.core_postimage (
    id bigint NOT NULL,
    image character varying(100) NOT NULL,
    alt_text character varying(255) NOT NULL,
    "order" integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    post_id bigint NOT NULL,
    CONSTRAINT core_postimage_order_check CHECK (("order" >= 0))
);


ALTER TABLE public.core_postimage OWNER TO us;

--
-- Name: core_postimage_id_seq; Type: SEQUENCE; Schema: public; Owner: us
--

ALTER TABLE public.core_postimage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_postimage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_postjob; Type: TABLE; Schema: public; Owner: us
--

CREATE TABLE public.core_postjob (
    id bigint NOT NULL,
    provider character varying(30) NOT NULL,
    payload jsonb NOT NULL,
    status character varying(20) NOT NULL,
    attempts integer NOT NULL,
    last_error text NOT NULL,
    remote_id character varying(255) NOT NULL,
    remote_url text NOT NULL,
    started_at timestamp with time zone,
    finished_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    client_id bigint NOT NULL,
    connection_id bigint,
    schedule_id bigint,
    CONSTRAINT core_postjob_attempts_check CHECK ((attempts >= 0))
);


ALTER TABLE public.core_postjob OWNER TO us;

--
-- Name: core_postjob_id_seq; Type: SEQUENCE; Schema: public; Owner: us
--

ALTER TABLE public.core_postjob ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_postjob_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_posttone; Type: TABLE; Schema: public; Owner: us
--

CREATE TABLE public.core_posttone (
    id bigint NOT NULL,
    value character varying(50) NOT NULL,
    label character varying(100) NOT NULL,
    is_default boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    client_id bigint
);


ALTER TABLE public.core_posttone OWNER TO us;

--
-- Name: core_posttone_id_seq; Type: SEQUENCE; Schema: public; Owner: us
--

ALTER TABLE public.core_posttone ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_posttone_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_posttype; Type: TABLE; Schema: public; Owner: us
--

CREATE TABLE public.core_posttype (
    id bigint NOT NULL,
    value character varying(50) NOT NULL,
    label character varying(100) NOT NULL,
    is_default boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    client_id bigint
);


ALTER TABLE public.core_posttype OWNER TO us;

--
-- Name: core_posttype_id_seq; Type: SEQUENCE; Schema: public; Owner: us
--

ALTER TABLE public.core_posttype ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_posttype_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_postvideo; Type: TABLE; Schema: public; Owner: us
--

CREATE TABLE public.core_postvideo (
    id bigint NOT NULL,
    video character varying(100) NOT NULL,
    caption character varying(255) NOT NULL,
    "order" integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    post_id bigint NOT NULL,
    CONSTRAINT core_postvideo_order_check CHECK (("order" >= 0))
);


ALTER TABLE public.core_postvideo OWNER TO us;

--
-- Name: core_postvideo_id_seq; Type: SEQUENCE; Schema: public; Owner: us
--

ALTER TABLE public.core_postvideo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_postvideo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_schedule; Type: TABLE; Schema: public; Owner: us
--

CREATE TABLE public.core_schedule (
    id bigint NOT NULL,
    scheduled_at timestamp with time zone NOT NULL,
    status character varying(20) NOT NULL,
    external_id character varying(255) NOT NULL,
    log text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    client_id bigint NOT NULL,
    post_id bigint NOT NULL,
    social_account_id bigint,
    connection_id bigint
);


ALTER TABLE public.core_schedule OWNER TO us;

--
-- Name: core_schedule_id_seq; Type: SEQUENCE; Schema: public; Owner: us
--

ALTER TABLE public.core_schedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_schedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_seokeywordset; Type: TABLE; Schema: public; Owner: us
--

CREATE TABLE public.core_seokeywordset (
    id bigint NOT NULL,
    status character varying(20) NOT NULL,
    keywords_text text NOT NULL,
    ai_model character varying(100) NOT NULL,
    prompt_used text NOT NULL,
    error_log text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    client_id bigint NOT NULL,
    topic_id bigint,
    keyword_groups jsonb NOT NULL,
    group_type character varying(32) NOT NULL,
    keywords_list jsonb NOT NULL
);


ALTER TABLE public.core_seokeywordset OWNER TO us;

--
-- Name: core_seokeywordset_id_seq; Type: SEQUENCE; Schema: public; Owner: us
--

ALTER TABLE public.core_seokeywordset ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_seokeywordset_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_socialaccount; Type: TABLE; Schema: public; Owner: us
--

CREATE TABLE public.core_socialaccount (
    id bigint NOT NULL,
    platform character varying(20) NOT NULL,
    name character varying(255) NOT NULL,
    access_token text NOT NULL,
    refresh_token text,
    extra jsonb NOT NULL,
    client_id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.core_socialaccount OWNER TO us;

--
-- Name: core_socialaccount_id_seq; Type: SEQUENCE; Schema: public; Owner: us
--

ALTER TABLE public.core_socialaccount ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_socialaccount_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_story; Type: TABLE; Schema: public; Owner: us
--

CREATE TABLE public.core_story (
    id bigint NOT NULL,
    title character varying(500) NOT NULL,
    episodes jsonb NOT NULL,
    episode_count integer NOT NULL,
    status character varying(20) NOT NULL,
    generated_by character varying(50) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    client_id bigint NOT NULL,
    created_by_id integer,
    template_id bigint,
    trend_item_id bigint
);


ALTER TABLE public.core_story OWNER TO us;

--
-- Name: core_story_id_seq; Type: SEQUENCE; Schema: public; Owner: us
--

ALTER TABLE public.core_story ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_story_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_systemsetting; Type: TABLE; Schema: public; Owner: us
--

CREATE TABLE public.core_systemsetting (
    id bigint NOT NULL,
    default_ai_model character varying(255) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    video_prompt_instructions text NOT NULL,
    image_generation_timeout integer NOT NULL,
    video_generation_timeout integer NOT NULL,
    fallback_ai_model character varying(255) NOT NULL,
    post_ai_model character varying(255) NOT NULL,
    image_openrouter_model character varying(255) NOT NULL,
    image_generation_method character varying(50) NOT NULL,
    photo_prompt_instructions text NOT NULL,
    CONSTRAINT core_systemsetting_image_generation_timeout_check CHECK ((image_generation_timeout >= 0)),
    CONSTRAINT core_systemsetting_video_generation_timeout_check CHECK ((video_generation_timeout >= 0))
);


ALTER TABLE public.core_systemsetting OWNER TO us;

--
-- Name: core_systemsetting_id_seq; Type: SEQUENCE; Schema: public; Owner: us
--

ALTER TABLE public.core_systemsetting ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_systemsetting_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_topic; Type: TABLE; Schema: public; Owner: us
--

CREATE TABLE public.core_topic (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    keywords jsonb NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    client_id bigint NOT NULL,
    use_google_trends boolean NOT NULL,
    use_instagram boolean NOT NULL,
    use_rss boolean NOT NULL,
    use_telegram boolean NOT NULL,
    use_youtube boolean NOT NULL,
    use_vkontakte boolean NOT NULL
);


ALTER TABLE public.core_topic OWNER TO us;

--
-- Name: core_topic_id_seq; Type: SEQUENCE; Schema: public; Owner: us
--

ALTER TABLE public.core_topic ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_topic_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_trenditem; Type: TABLE; Schema: public; Owner: us
--

CREATE TABLE public.core_trenditem (
    id bigint NOT NULL,
    source character varying(30) NOT NULL,
    title character varying(500) NOT NULL,
    description text NOT NULL,
    url character varying(1000) NOT NULL,
    relevance_score integer NOT NULL,
    extra jsonb NOT NULL,
    discovered_at timestamp with time zone NOT NULL,
    client_id bigint NOT NULL,
    topic_id bigint NOT NULL,
    used_for_post_id bigint
);


ALTER TABLE public.core_trenditem OWNER TO us;

--
-- Name: core_trenditem_id_seq; Type: SEQUENCE; Schema: public; Owner: us
--

ALTER TABLE public.core_trenditem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_trenditem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_usertenantrole; Type: TABLE; Schema: public; Owner: us
--

CREATE TABLE public.core_usertenantrole (
    id bigint NOT NULL,
    role character varying(20) NOT NULL,
    client_id bigint NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.core_usertenantrole OWNER TO us;

--
-- Name: core_usertenantrole_id_seq; Type: SEQUENCE; Schema: public; Owner: us
--

ALTER TABLE public.core_usertenantrole ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_usertenantrole_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_vkintegration; Type: TABLE; Schema: public; Owner: us
--

CREATE TABLE public.core_vkintegration (
    id bigint NOT NULL,
    group_id bigint NOT NULL,
    group_name character varying(255) NOT NULL,
    screen_name character varying(255) NOT NULL,
    access_token text NOT NULL,
    user_id bigint,
    status character varying(30) NOT NULL,
    last_published_at timestamp with time zone,
    extra jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    client_id bigint NOT NULL,
    owner_id integer NOT NULL
);


ALTER TABLE public.core_vkintegration OWNER TO us;

--
-- Name: core_vkintegration_id_seq; Type: SEQUENCE; Schema: public; Owner: us
--

ALTER TABLE public.core_vkintegration ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_vkintegration_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_weeklysourcebatch; Type: TABLE; Schema: public; Owner: us
--

CREATE TABLE public.core_weeklysourcebatch (
    id bigint NOT NULL,
    week_start date NOT NULL,
    status character varying(20) DEFAULT 'pending'::character varying NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    client_id bigint NOT NULL
);


ALTER TABLE public.core_weeklysourcebatch OWNER TO us;

--
-- Name: core_weeklysourcebatch_id_seq; Type: SEQUENCE; Schema: public; Owner: us
--

CREATE SEQUENCE public.core_weeklysourcebatch_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.core_weeklysourcebatch_id_seq OWNER TO us;

--
-- Name: core_weeklysourcebatch_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: us
--

ALTER SEQUENCE public.core_weeklysourcebatch_id_seq OWNED BY public.core_weeklysourcebatch.id;


--
-- Name: core_weeklysourcereport; Type: TABLE; Schema: public; Owner: us
--

CREATE TABLE public.core_weeklysourcereport (
    id bigint NOT NULL,
    source_type character varying(20) NOT NULL,
    source_value character varying(255) NOT NULL,
    week_start date NOT NULL,
    status character varying(20) NOT NULL,
    summary text NOT NULL,
    links jsonb NOT NULL,
    error text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    client_id bigint NOT NULL,
    batch_id bigint
);


ALTER TABLE public.core_weeklysourcereport OWNER TO us;

--
-- Name: core_weeklysourcereport_id_seq; Type: SEQUENCE; Schema: public; Owner: us
--

ALTER TABLE public.core_weeklysourcereport ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_weeklysourcereport_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_wordstatquery; Type: TABLE; Schema: public; Owner: us
--

CREATE TABLE public.core_wordstatquery (
    id bigint NOT NULL,
    request_phrase character varying(255) NOT NULL,
    total_count integer NOT NULL,
    include_parent boolean NOT NULL,
    regions jsonb NOT NULL,
    devices jsonb NOT NULL,
    user_login character varying(255) NOT NULL,
    limit_per_second integer,
    daily_limit integer,
    daily_limit_remaining integer,
    raw_response jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    client_id bigint NOT NULL,
    phrases jsonb NOT NULL,
    group_name character varying(255) NOT NULL,
    CONSTRAINT core_wordstatquery_daily_limit_check CHECK ((daily_limit >= 0)),
    CONSTRAINT core_wordstatquery_daily_limit_remaining_check CHECK ((daily_limit_remaining >= 0)),
    CONSTRAINT core_wordstatquery_limit_per_second_check CHECK ((limit_per_second >= 0)),
    CONSTRAINT core_wordstatquery_total_count_check CHECK ((total_count >= 0))
);


ALTER TABLE public.core_wordstatquery OWNER TO us;

--
-- Name: core_wordstatquery_id_seq; Type: SEQUENCE; Schema: public; Owner: us
--

ALTER TABLE public.core_wordstatquery ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_wordstatquery_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_wordstatresult; Type: TABLE; Schema: public; Owner: us
--

CREATE TABLE public.core_wordstatresult (
    id bigint NOT NULL,
    phrase text NOT NULL,
    count integer NOT NULL,
    result_type character varying(20) NOT NULL,
    query_id bigint NOT NULL,
    used_in_post integer NOT NULL,
    CONSTRAINT core_wordstatresult_count_check CHECK ((count >= 0)),
    CONSTRAINT core_wordstatresult_used_in_post_check CHECK ((used_in_post >= 0))
);


ALTER TABLE public.core_wordstatresult OWNER TO us;

--
-- Name: core_wordstatresult_id_seq; Type: SEQUENCE; Schema: public; Owner: us
--

ALTER TABLE public.core_wordstatresult ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_wordstatresult_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: home_homepage; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.home_homepage (
    page_ptr_id integer NOT NULL
);


ALTER TABLE public.home_homepage OWNER TO postgres;

--
-- Name: taggit_tag; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.taggit_tag (
    id integer NOT NULL,
    name character varying(100) NOT NULL,
    slug character varying(100) NOT NULL
);


ALTER TABLE public.taggit_tag OWNER TO postgres;

--
-- Name: taggit_tag_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.taggit_tag ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.taggit_tag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: taggit_taggeditem; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.taggit_taggeditem (
    id integer NOT NULL,
    object_id integer NOT NULL,
    content_type_id integer NOT NULL,
    tag_id integer NOT NULL
);


ALTER TABLE public.taggit_taggeditem OWNER TO postgres;

--
-- Name: taggit_taggeditem_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.taggit_taggeditem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.taggit_taggeditem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wagtailadmin_admin; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wagtailadmin_admin (
    id integer NOT NULL
);


ALTER TABLE public.wagtailadmin_admin OWNER TO postgres;

--
-- Name: wagtailadmin_admin_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.wagtailadmin_admin ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wagtailadmin_admin_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wagtailadmin_editingsession; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wagtailadmin_editingsession (
    id integer NOT NULL,
    object_id character varying(255) NOT NULL,
    last_seen_at timestamp with time zone NOT NULL,
    content_type_id integer NOT NULL,
    user_id integer NOT NULL,
    is_editing boolean NOT NULL
);


ALTER TABLE public.wagtailadmin_editingsession OWNER TO postgres;

--
-- Name: wagtailadmin_editingsession_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.wagtailadmin_editingsession ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wagtailadmin_editingsession_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wagtailcore_collection; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wagtailcore_collection (
    id integer NOT NULL,
    path character varying(255) NOT NULL COLLATE pg_catalog."C",
    depth integer NOT NULL,
    numchild integer NOT NULL,
    name character varying(255) NOT NULL,
    CONSTRAINT wagtailcore_collection_depth_check CHECK ((depth >= 0)),
    CONSTRAINT wagtailcore_collection_numchild_check CHECK ((numchild >= 0))
);


ALTER TABLE public.wagtailcore_collection OWNER TO postgres;

--
-- Name: wagtailcore_collection_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.wagtailcore_collection ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wagtailcore_collection_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wagtailcore_collectionviewrestriction; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wagtailcore_collectionviewrestriction (
    id integer NOT NULL,
    restriction_type character varying(20) NOT NULL,
    password character varying(255) NOT NULL,
    collection_id integer NOT NULL
);


ALTER TABLE public.wagtailcore_collectionviewrestriction OWNER TO postgres;

--
-- Name: wagtailcore_collectionviewrestriction_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wagtailcore_collectionviewrestriction_groups (
    id bigint NOT NULL,
    collectionviewrestriction_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.wagtailcore_collectionviewrestriction_groups OWNER TO postgres;

--
-- Name: wagtailcore_collectionviewrestriction_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.wagtailcore_collectionviewrestriction_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wagtailcore_collectionviewrestriction_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wagtailcore_collectionviewrestriction_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.wagtailcore_collectionviewrestriction ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wagtailcore_collectionviewrestriction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wagtailcore_comment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wagtailcore_comment (
    id integer NOT NULL,
    text text NOT NULL,
    contentpath text NOT NULL,
    "position" text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    resolved_at timestamp with time zone,
    page_id integer NOT NULL,
    resolved_by_id integer,
    revision_created_id integer,
    user_id integer NOT NULL
);


ALTER TABLE public.wagtailcore_comment OWNER TO postgres;

--
-- Name: wagtailcore_comment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.wagtailcore_comment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wagtailcore_comment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wagtailcore_commentreply; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wagtailcore_commentreply (
    id integer NOT NULL,
    text text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    comment_id integer NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.wagtailcore_commentreply OWNER TO postgres;

--
-- Name: wagtailcore_commentreply_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.wagtailcore_commentreply ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wagtailcore_commentreply_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wagtailcore_groupapprovaltask; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wagtailcore_groupapprovaltask (
    task_ptr_id integer NOT NULL
);


ALTER TABLE public.wagtailcore_groupapprovaltask OWNER TO postgres;

--
-- Name: wagtailcore_groupapprovaltask_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wagtailcore_groupapprovaltask_groups (
    id bigint NOT NULL,
    groupapprovaltask_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.wagtailcore_groupapprovaltask_groups OWNER TO postgres;

--
-- Name: wagtailcore_groupapprovaltask_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.wagtailcore_groupapprovaltask_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wagtailcore_groupapprovaltask_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wagtailcore_groupcollectionpermission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wagtailcore_groupcollectionpermission (
    id integer NOT NULL,
    collection_id integer NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.wagtailcore_groupcollectionpermission OWNER TO postgres;

--
-- Name: wagtailcore_groupcollectionpermission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.wagtailcore_groupcollectionpermission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wagtailcore_groupcollectionpermission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wagtailcore_grouppagepermission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wagtailcore_grouppagepermission (
    id integer NOT NULL,
    group_id integer NOT NULL,
    page_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.wagtailcore_grouppagepermission OWNER TO postgres;

--
-- Name: wagtailcore_grouppagepermission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.wagtailcore_grouppagepermission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wagtailcore_grouppagepermission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wagtailcore_groupsitepermission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wagtailcore_groupsitepermission (
    id integer NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL,
    site_id integer NOT NULL
);


ALTER TABLE public.wagtailcore_groupsitepermission OWNER TO postgres;

--
-- Name: wagtailcore_groupsitepermission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.wagtailcore_groupsitepermission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wagtailcore_groupsitepermission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wagtailcore_locale; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wagtailcore_locale (
    id integer NOT NULL,
    language_code character varying(100) NOT NULL
);


ALTER TABLE public.wagtailcore_locale OWNER TO postgres;

--
-- Name: wagtailcore_locale_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.wagtailcore_locale ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wagtailcore_locale_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wagtailcore_modellogentry; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wagtailcore_modellogentry (
    id integer NOT NULL,
    label text NOT NULL,
    action character varying(255) NOT NULL,
    data jsonb NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    content_changed boolean NOT NULL,
    deleted boolean NOT NULL,
    object_id character varying(255) NOT NULL,
    content_type_id integer,
    user_id integer,
    uuid uuid,
    revision_id integer
);


ALTER TABLE public.wagtailcore_modellogentry OWNER TO postgres;

--
-- Name: wagtailcore_modellogentry_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.wagtailcore_modellogentry ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wagtailcore_modellogentry_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wagtailcore_page; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wagtailcore_page (
    id integer NOT NULL,
    path character varying(255) NOT NULL COLLATE pg_catalog."C",
    depth integer NOT NULL,
    numchild integer NOT NULL,
    title character varying(255) NOT NULL,
    slug character varying(255) NOT NULL,
    live boolean NOT NULL,
    has_unpublished_changes boolean NOT NULL,
    url_path text NOT NULL,
    seo_title character varying(255) NOT NULL,
    show_in_menus boolean NOT NULL,
    search_description text NOT NULL,
    go_live_at timestamp with time zone,
    expire_at timestamp with time zone,
    expired boolean NOT NULL,
    content_type_id integer NOT NULL,
    owner_id integer,
    locked boolean NOT NULL,
    latest_revision_created_at timestamp with time zone,
    first_published_at timestamp with time zone,
    live_revision_id integer,
    last_published_at timestamp with time zone,
    draft_title character varying(255) NOT NULL,
    locked_at timestamp with time zone,
    locked_by_id integer,
    translation_key uuid NOT NULL,
    locale_id integer NOT NULL,
    alias_of_id integer,
    latest_revision_id integer,
    CONSTRAINT wagtailcore_page_depth_check CHECK ((depth >= 0)),
    CONSTRAINT wagtailcore_page_numchild_check CHECK ((numchild >= 0))
);


ALTER TABLE public.wagtailcore_page OWNER TO postgres;

--
-- Name: wagtailcore_page_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.wagtailcore_page ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wagtailcore_page_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wagtailcore_pagelogentry; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wagtailcore_pagelogentry (
    id integer NOT NULL,
    label text NOT NULL,
    action character varying(255) NOT NULL,
    data jsonb NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    content_changed boolean NOT NULL,
    deleted boolean NOT NULL,
    content_type_id integer,
    page_id integer NOT NULL,
    revision_id integer,
    user_id integer,
    uuid uuid
);


ALTER TABLE public.wagtailcore_pagelogentry OWNER TO postgres;

--
-- Name: wagtailcore_pagelogentry_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.wagtailcore_pagelogentry ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wagtailcore_pagelogentry_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wagtailcore_revision; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wagtailcore_revision (
    id integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    content jsonb NOT NULL,
    approved_go_live_at timestamp with time zone,
    object_id character varying(255) NOT NULL,
    user_id integer,
    content_type_id integer NOT NULL,
    base_content_type_id integer NOT NULL,
    object_str text NOT NULL
);


ALTER TABLE public.wagtailcore_revision OWNER TO postgres;

--
-- Name: wagtailcore_pagerevision_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.wagtailcore_revision ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wagtailcore_pagerevision_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wagtailcore_pagesubscription; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wagtailcore_pagesubscription (
    id integer NOT NULL,
    comment_notifications boolean NOT NULL,
    page_id integer NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.wagtailcore_pagesubscription OWNER TO postgres;

--
-- Name: wagtailcore_pagesubscription_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.wagtailcore_pagesubscription ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wagtailcore_pagesubscription_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wagtailcore_pageviewrestriction; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wagtailcore_pageviewrestriction (
    id integer NOT NULL,
    password character varying(255) NOT NULL,
    page_id integer NOT NULL,
    restriction_type character varying(20) NOT NULL
);


ALTER TABLE public.wagtailcore_pageviewrestriction OWNER TO postgres;

--
-- Name: wagtailcore_pageviewrestriction_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wagtailcore_pageviewrestriction_groups (
    id bigint NOT NULL,
    pageviewrestriction_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.wagtailcore_pageviewrestriction_groups OWNER TO postgres;

--
-- Name: wagtailcore_pageviewrestriction_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.wagtailcore_pageviewrestriction_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wagtailcore_pageviewrestriction_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wagtailcore_pageviewrestriction_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.wagtailcore_pageviewrestriction ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wagtailcore_pageviewrestriction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wagtailcore_referenceindex; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wagtailcore_referenceindex (
    id integer NOT NULL,
    object_id character varying(255) NOT NULL,
    to_object_id character varying(255) NOT NULL,
    model_path text NOT NULL,
    content_path text NOT NULL,
    content_path_hash uuid NOT NULL,
    base_content_type_id integer NOT NULL,
    content_type_id integer NOT NULL,
    to_content_type_id integer NOT NULL
);


ALTER TABLE public.wagtailcore_referenceindex OWNER TO postgres;

--
-- Name: wagtailcore_referenceindex_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.wagtailcore_referenceindex ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wagtailcore_referenceindex_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wagtailcore_site; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wagtailcore_site (
    id integer NOT NULL,
    hostname character varying(255) NOT NULL,
    port integer NOT NULL,
    is_default_site boolean NOT NULL,
    root_page_id integer NOT NULL,
    site_name character varying(255) NOT NULL
);


ALTER TABLE public.wagtailcore_site OWNER TO postgres;

--
-- Name: wagtailcore_site_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.wagtailcore_site ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wagtailcore_site_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wagtailcore_task; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wagtailcore_task (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    active boolean NOT NULL,
    content_type_id integer NOT NULL
);


ALTER TABLE public.wagtailcore_task OWNER TO postgres;

--
-- Name: wagtailcore_task_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.wagtailcore_task ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wagtailcore_task_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wagtailcore_taskstate; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wagtailcore_taskstate (
    id integer NOT NULL,
    status character varying(50) NOT NULL,
    started_at timestamp with time zone NOT NULL,
    finished_at timestamp with time zone,
    content_type_id integer NOT NULL,
    revision_id integer NOT NULL,
    task_id integer NOT NULL,
    workflow_state_id integer NOT NULL,
    finished_by_id integer,
    comment text NOT NULL
);


ALTER TABLE public.wagtailcore_taskstate OWNER TO postgres;

--
-- Name: wagtailcore_taskstate_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.wagtailcore_taskstate ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wagtailcore_taskstate_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wagtailcore_uploadedfile; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wagtailcore_uploadedfile (
    id integer NOT NULL,
    file character varying(200) NOT NULL,
    for_content_type_id integer,
    uploaded_by_user_id integer
);


ALTER TABLE public.wagtailcore_uploadedfile OWNER TO postgres;

--
-- Name: wagtailcore_uploadedfile_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.wagtailcore_uploadedfile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wagtailcore_uploadedfile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wagtailcore_workflow; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wagtailcore_workflow (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    active boolean NOT NULL
);


ALTER TABLE public.wagtailcore_workflow OWNER TO postgres;

--
-- Name: wagtailcore_workflow_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.wagtailcore_workflow ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wagtailcore_workflow_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wagtailcore_workflowcontenttype; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wagtailcore_workflowcontenttype (
    content_type_id integer NOT NULL,
    workflow_id integer NOT NULL
);


ALTER TABLE public.wagtailcore_workflowcontenttype OWNER TO postgres;

--
-- Name: wagtailcore_workflowpage; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wagtailcore_workflowpage (
    page_id integer NOT NULL,
    workflow_id integer NOT NULL
);


ALTER TABLE public.wagtailcore_workflowpage OWNER TO postgres;

--
-- Name: wagtailcore_workflowstate; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wagtailcore_workflowstate (
    id integer NOT NULL,
    status character varying(50) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    current_task_state_id integer,
    object_id character varying(255) NOT NULL,
    requested_by_id integer,
    workflow_id integer NOT NULL,
    content_type_id integer NOT NULL,
    base_content_type_id integer NOT NULL
);


ALTER TABLE public.wagtailcore_workflowstate OWNER TO postgres;

--
-- Name: wagtailcore_workflowstate_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.wagtailcore_workflowstate ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wagtailcore_workflowstate_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wagtailcore_workflowtask; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wagtailcore_workflowtask (
    id integer NOT NULL,
    sort_order integer,
    task_id integer NOT NULL,
    workflow_id integer NOT NULL
);


ALTER TABLE public.wagtailcore_workflowtask OWNER TO postgres;

--
-- Name: wagtailcore_workflowtask_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.wagtailcore_workflowtask ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wagtailcore_workflowtask_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wagtaildocs_document; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wagtaildocs_document (
    id integer NOT NULL,
    title character varying(255) NOT NULL,
    file character varying(100) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    uploaded_by_user_id integer,
    collection_id integer NOT NULL,
    file_size bigint,
    file_hash character varying(40) NOT NULL,
    CONSTRAINT wagtaildocs_document_file_size_check CHECK ((file_size >= 0))
);


ALTER TABLE public.wagtaildocs_document OWNER TO postgres;

--
-- Name: wagtaildocs_document_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.wagtaildocs_document ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wagtaildocs_document_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wagtailembeds_embed; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wagtailembeds_embed (
    id integer NOT NULL,
    url text NOT NULL,
    max_width smallint,
    type character varying(10) NOT NULL,
    html text NOT NULL,
    title text NOT NULL,
    author_name text NOT NULL,
    provider_name text NOT NULL,
    thumbnail_url text NOT NULL,
    width integer,
    height integer,
    last_updated timestamp with time zone NOT NULL,
    hash character varying(32) NOT NULL,
    cache_until timestamp with time zone
);


ALTER TABLE public.wagtailembeds_embed OWNER TO postgres;

--
-- Name: wagtailembeds_embed_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.wagtailembeds_embed ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wagtailembeds_embed_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wagtailforms_formsubmission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wagtailforms_formsubmission (
    id integer NOT NULL,
    form_data jsonb NOT NULL,
    submit_time timestamp with time zone NOT NULL,
    page_id integer NOT NULL
);


ALTER TABLE public.wagtailforms_formsubmission OWNER TO postgres;

--
-- Name: wagtailforms_formsubmission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.wagtailforms_formsubmission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wagtailforms_formsubmission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wagtailimages_image; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wagtailimages_image (
    id integer NOT NULL,
    title character varying(255) NOT NULL,
    file character varying(100) NOT NULL,
    width integer NOT NULL,
    height integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    focal_point_x integer,
    focal_point_y integer,
    focal_point_width integer,
    focal_point_height integer,
    uploaded_by_user_id integer,
    file_size integer,
    collection_id integer NOT NULL,
    file_hash character varying(40) NOT NULL,
    description character varying(255) NOT NULL,
    CONSTRAINT wagtailimages_image_file_size_check CHECK ((file_size >= 0)),
    CONSTRAINT wagtailimages_image_focal_point_height_check CHECK ((focal_point_height >= 0)),
    CONSTRAINT wagtailimages_image_focal_point_width_check CHECK ((focal_point_width >= 0)),
    CONSTRAINT wagtailimages_image_focal_point_x_check CHECK ((focal_point_x >= 0)),
    CONSTRAINT wagtailimages_image_focal_point_y_check CHECK ((focal_point_y >= 0))
);


ALTER TABLE public.wagtailimages_image OWNER TO postgres;

--
-- Name: wagtailimages_image_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.wagtailimages_image ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wagtailimages_image_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wagtailimages_rendition; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wagtailimages_rendition (
    id integer NOT NULL,
    file character varying(100) NOT NULL,
    width integer NOT NULL,
    height integer NOT NULL,
    focal_point_key character varying(16) NOT NULL,
    filter_spec character varying(255) NOT NULL,
    image_id integer NOT NULL
);


ALTER TABLE public.wagtailimages_rendition OWNER TO postgres;

--
-- Name: wagtailimages_rendition_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.wagtailimages_rendition ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wagtailimages_rendition_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wagtailredirects_redirect; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wagtailredirects_redirect (
    id integer NOT NULL,
    old_path character varying(255) NOT NULL,
    is_permanent boolean NOT NULL,
    redirect_link character varying(255) NOT NULL,
    redirect_page_id integer,
    site_id integer,
    automatically_created boolean NOT NULL,
    created_at timestamp with time zone,
    redirect_page_route_path character varying(255) NOT NULL
);


ALTER TABLE public.wagtailredirects_redirect OWNER TO postgres;

--
-- Name: wagtailredirects_redirect_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.wagtailredirects_redirect ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wagtailredirects_redirect_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wagtailsearch_indexentry; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wagtailsearch_indexentry (
    id integer NOT NULL,
    object_id character varying(50) NOT NULL,
    title_norm double precision NOT NULL,
    content_type_id integer NOT NULL,
    autocomplete tsvector NOT NULL,
    title tsvector NOT NULL,
    body tsvector NOT NULL
);


ALTER TABLE public.wagtailsearch_indexentry OWNER TO postgres;

--
-- Name: wagtailsearch_indexentry_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.wagtailsearch_indexentry ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wagtailsearch_indexentry_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wagtailusers_userprofile; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wagtailusers_userprofile (
    id integer NOT NULL,
    submitted_notifications boolean NOT NULL,
    approved_notifications boolean NOT NULL,
    rejected_notifications boolean NOT NULL,
    user_id integer NOT NULL,
    preferred_language character varying(10) NOT NULL,
    current_time_zone character varying(40) NOT NULL,
    avatar character varying(100) NOT NULL,
    updated_comments_notifications boolean NOT NULL,
    dismissibles jsonb NOT NULL,
    theme character varying(40) NOT NULL,
    density character varying(40) NOT NULL,
    contrast character varying(40) NOT NULL,
    keyboard_shortcuts boolean NOT NULL
);


ALTER TABLE public.wagtailusers_userprofile OWNER TO postgres;

--
-- Name: wagtailusers_userprofile_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.wagtailusers_userprofile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wagtailusers_userprofile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_weeklysourcebatch id; Type: DEFAULT; Schema: public; Owner: us
--

ALTER TABLE ONLY public.core_weeklysourcebatch ALTER COLUMN id SET DEFAULT nextval('public.core_weeklysourcebatch_id_seq'::regclass);


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: pg_database_owner
--

GRANT ALL ON SCHEMA public TO us;


--
-- Name: TABLE auth_group; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.auth_group TO us;


--
-- Name: SEQUENCE auth_group_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.auth_group_id_seq TO us;


--
-- Name: TABLE auth_group_permissions; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.auth_group_permissions TO us;


--
-- Name: SEQUENCE auth_group_permissions_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.auth_group_permissions_id_seq TO us;


--
-- Name: TABLE auth_permission; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.auth_permission TO us;


--
-- Name: SEQUENCE auth_permission_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.auth_permission_id_seq TO us;


--
-- Name: TABLE auth_user; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.auth_user TO us;


--
-- Name: TABLE auth_user_groups; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.auth_user_groups TO us;


--
-- Name: SEQUENCE auth_user_groups_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.auth_user_groups_id_seq TO us;


--
-- Name: SEQUENCE auth_user_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.auth_user_id_seq TO us;


--
-- Name: TABLE auth_user_user_permissions; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.auth_user_user_permissions TO us;


--
-- Name: SEQUENCE auth_user_user_permissions_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.auth_user_user_permissions_id_seq TO us;


--
-- Name: TABLE django_admin_log; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.django_admin_log TO us;


--
-- Name: SEQUENCE django_admin_log_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.django_admin_log_id_seq TO us;


--
-- Name: TABLE django_content_type; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.django_content_type TO us;


--
-- Name: SEQUENCE django_content_type_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.django_content_type_id_seq TO us;


--
-- Name: TABLE django_migrations; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.django_migrations TO us;


--
-- Name: SEQUENCE django_migrations_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.django_migrations_id_seq TO us;


--
-- Name: TABLE django_session; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.django_session TO us;


--
-- Name: TABLE home_homepage; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.home_homepage TO us;


--
-- Name: TABLE taggit_tag; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.taggit_tag TO us;


--
-- Name: SEQUENCE taggit_tag_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.taggit_tag_id_seq TO us;


--
-- Name: TABLE taggit_taggeditem; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.taggit_taggeditem TO us;


--
-- Name: SEQUENCE taggit_taggeditem_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.taggit_taggeditem_id_seq TO us;


--
-- Name: TABLE wagtailadmin_admin; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.wagtailadmin_admin TO us;


--
-- Name: SEQUENCE wagtailadmin_admin_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.wagtailadmin_admin_id_seq TO us;


--
-- Name: TABLE wagtailadmin_editingsession; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.wagtailadmin_editingsession TO us;


--
-- Name: SEQUENCE wagtailadmin_editingsession_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.wagtailadmin_editingsession_id_seq TO us;


--
-- Name: TABLE wagtailcore_collection; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.wagtailcore_collection TO us;


--
-- Name: SEQUENCE wagtailcore_collection_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.wagtailcore_collection_id_seq TO us;


--
-- Name: TABLE wagtailcore_collectionviewrestriction; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.wagtailcore_collectionviewrestriction TO us;


--
-- Name: TABLE wagtailcore_collectionviewrestriction_groups; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.wagtailcore_collectionviewrestriction_groups TO us;


--
-- Name: SEQUENCE wagtailcore_collectionviewrestriction_groups_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.wagtailcore_collectionviewrestriction_groups_id_seq TO us;


--
-- Name: SEQUENCE wagtailcore_collectionviewrestriction_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.wagtailcore_collectionviewrestriction_id_seq TO us;


--
-- Name: TABLE wagtailcore_comment; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.wagtailcore_comment TO us;


--
-- Name: SEQUENCE wagtailcore_comment_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.wagtailcore_comment_id_seq TO us;


--
-- Name: TABLE wagtailcore_commentreply; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.wagtailcore_commentreply TO us;


--
-- Name: SEQUENCE wagtailcore_commentreply_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.wagtailcore_commentreply_id_seq TO us;


--
-- Name: TABLE wagtailcore_groupapprovaltask; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.wagtailcore_groupapprovaltask TO us;


--
-- Name: TABLE wagtailcore_groupapprovaltask_groups; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.wagtailcore_groupapprovaltask_groups TO us;


--
-- Name: SEQUENCE wagtailcore_groupapprovaltask_groups_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.wagtailcore_groupapprovaltask_groups_id_seq TO us;


--
-- Name: TABLE wagtailcore_groupcollectionpermission; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.wagtailcore_groupcollectionpermission TO us;


--
-- Name: SEQUENCE wagtailcore_groupcollectionpermission_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.wagtailcore_groupcollectionpermission_id_seq TO us;


--
-- Name: TABLE wagtailcore_grouppagepermission; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.wagtailcore_grouppagepermission TO us;


--
-- Name: SEQUENCE wagtailcore_grouppagepermission_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.wagtailcore_grouppagepermission_id_seq TO us;


--
-- Name: TABLE wagtailcore_groupsitepermission; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.wagtailcore_groupsitepermission TO us;


--
-- Name: SEQUENCE wagtailcore_groupsitepermission_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.wagtailcore_groupsitepermission_id_seq TO us;


--
-- Name: TABLE wagtailcore_locale; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.wagtailcore_locale TO us;


--
-- Name: SEQUENCE wagtailcore_locale_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.wagtailcore_locale_id_seq TO us;


--
-- Name: TABLE wagtailcore_modellogentry; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.wagtailcore_modellogentry TO us;


--
-- Name: SEQUENCE wagtailcore_modellogentry_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.wagtailcore_modellogentry_id_seq TO us;


--
-- Name: TABLE wagtailcore_page; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.wagtailcore_page TO us;


--
-- Name: SEQUENCE wagtailcore_page_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.wagtailcore_page_id_seq TO us;


--
-- Name: TABLE wagtailcore_pagelogentry; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.wagtailcore_pagelogentry TO us;


--
-- Name: SEQUENCE wagtailcore_pagelogentry_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.wagtailcore_pagelogentry_id_seq TO us;


--
-- Name: TABLE wagtailcore_revision; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.wagtailcore_revision TO us;


--
-- Name: SEQUENCE wagtailcore_pagerevision_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.wagtailcore_pagerevision_id_seq TO us;


--
-- Name: TABLE wagtailcore_pagesubscription; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.wagtailcore_pagesubscription TO us;


--
-- Name: SEQUENCE wagtailcore_pagesubscription_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.wagtailcore_pagesubscription_id_seq TO us;


--
-- Name: TABLE wagtailcore_pageviewrestriction; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.wagtailcore_pageviewrestriction TO us;


--
-- Name: TABLE wagtailcore_pageviewrestriction_groups; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.wagtailcore_pageviewrestriction_groups TO us;


--
-- Name: SEQUENCE wagtailcore_pageviewrestriction_groups_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.wagtailcore_pageviewrestriction_groups_id_seq TO us;


--
-- Name: SEQUENCE wagtailcore_pageviewrestriction_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.wagtailcore_pageviewrestriction_id_seq TO us;


--
-- Name: TABLE wagtailcore_referenceindex; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.wagtailcore_referenceindex TO us;


--
-- Name: SEQUENCE wagtailcore_referenceindex_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.wagtailcore_referenceindex_id_seq TO us;


--
-- Name: TABLE wagtailcore_site; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.wagtailcore_site TO us;


--
-- Name: SEQUENCE wagtailcore_site_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.wagtailcore_site_id_seq TO us;


--
-- Name: TABLE wagtailcore_task; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.wagtailcore_task TO us;


--
-- Name: SEQUENCE wagtailcore_task_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.wagtailcore_task_id_seq TO us;


--
-- Name: TABLE wagtailcore_taskstate; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.wagtailcore_taskstate TO us;


--
-- Name: SEQUENCE wagtailcore_taskstate_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.wagtailcore_taskstate_id_seq TO us;


--
-- Name: TABLE wagtailcore_uploadedfile; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.wagtailcore_uploadedfile TO us;


--
-- Name: SEQUENCE wagtailcore_uploadedfile_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.wagtailcore_uploadedfile_id_seq TO us;


--
-- Name: TABLE wagtailcore_workflow; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.wagtailcore_workflow TO us;


--
-- Name: SEQUENCE wagtailcore_workflow_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.wagtailcore_workflow_id_seq TO us;


--
-- Name: TABLE wagtailcore_workflowcontenttype; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.wagtailcore_workflowcontenttype TO us;


--
-- Name: TABLE wagtailcore_workflowpage; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.wagtailcore_workflowpage TO us;


--
-- Name: TABLE wagtailcore_workflowstate; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.wagtailcore_workflowstate TO us;


--
-- Name: SEQUENCE wagtailcore_workflowstate_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.wagtailcore_workflowstate_id_seq TO us;


--
-- Name: TABLE wagtailcore_workflowtask; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.wagtailcore_workflowtask TO us;


--
-- Name: SEQUENCE wagtailcore_workflowtask_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.wagtailcore_workflowtask_id_seq TO us;


--
-- Name: TABLE wagtaildocs_document; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.wagtaildocs_document TO us;


--
-- Name: SEQUENCE wagtaildocs_document_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.wagtaildocs_document_id_seq TO us;


--
-- Name: TABLE wagtailembeds_embed; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.wagtailembeds_embed TO us;


--
-- Name: SEQUENCE wagtailembeds_embed_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.wagtailembeds_embed_id_seq TO us;


--
-- Name: TABLE wagtailforms_formsubmission; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.wagtailforms_formsubmission TO us;


--
-- Name: SEQUENCE wagtailforms_formsubmission_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.wagtailforms_formsubmission_id_seq TO us;


--
-- Name: TABLE wagtailimages_image; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.wagtailimages_image TO us;


--
-- Name: SEQUENCE wagtailimages_image_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.wagtailimages_image_id_seq TO us;


--
-- Name: TABLE wagtailimages_rendition; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.wagtailimages_rendition TO us;


--
-- Name: SEQUENCE wagtailimages_rendition_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.wagtailimages_rendition_id_seq TO us;


--
-- Name: TABLE wagtailredirects_redirect; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.wagtailredirects_redirect TO us;


--
-- Name: SEQUENCE wagtailredirects_redirect_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.wagtailredirects_redirect_id_seq TO us;


--
-- Name: TABLE wagtailsearch_indexentry; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.wagtailsearch_indexentry TO us;


--
-- Name: SEQUENCE wagtailsearch_indexentry_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.wagtailsearch_indexentry_id_seq TO us;


--
-- Name: TABLE wagtailusers_userprofile; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.wagtailusers_userprofile TO us;


--
-- Name: SEQUENCE wagtailusers_userprofile_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.wagtailusers_userprofile_id_seq TO us;


--
-- PostgreSQL database dump complete
--

\unrestrict WL0AnVSf5pPg7KC8guvzi0C03DywOr8jYVhluDHg69OPPM8oXI35e2xnKwarB0T

