# Generated by Django 5.2.8 on 2025-11-26 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Название темы (например, 'студия танцев')", max_length=255)),
                ('keywords', models.JSONField(blank=True, default=list, help_text="Ключевые слова для поиска (например, ['танцы', 'хореография', 'dance'])")),
                ('is_active', models.BooleanField(default=True, help_text='Активна ли тема для автоматического сбора')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='core.client')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TrendItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('google_trends', 'Google Trends'), ('google_news_rss', 'Google News RSS'), ('youtube', 'YouTube'), ('rss_feed', 'RSS Feed'), ('news_api', 'News API'), ('manual', 'Manual')], max_length=30)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True, max_length=1000)),
                ('relevance_score', models.IntegerField(default=0, help_text='Оценка релевантности (например, количество поисков для трендов)')),
                ('extra', models.JSONField(blank=True, default=dict, help_text='Дополнительные данные (автор, дата публикации, изображение и т.д.)')),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trend_items', to='core.client')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trend_items', to='core.topic')),
                ('used_for_post', models.ForeignKey(blank=True, help_text='Пост, созданный на основе этого тренда', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_trends', to='core.post')),
            ],
            options={
                'verbose_name': 'Trend Item',
                'verbose_name_plural': 'Trend Items',
                'ordering': ('-relevance_score', '-discovered_at'),
            },
        ),
    ]
