# Generated by Django 5.2.8 on 2025-11-26 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_topic_trenditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Название шаблона (например, 'Instagram пост')", max_length=255)),
                ('tone', models.CharField(choices=[('professional', 'Профессиональный'), ('friendly', 'Дружественный'), ('informative', 'Информационный'), ('casual', 'Непринуждённый'), ('enthusiastic', 'Восторженный')], default='professional', help_text='Тон контента', max_length=20)),
                ('length', models.CharField(choices=[('short', 'Короткий (до 280 символов)'), ('medium', 'Средний (280-500 символов)'), ('long', 'Длинный (500-1000 символов)')], default='medium', help_text='Длина поста', max_length=20)),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English')], default='ru', help_text='Язык контента', max_length=5)),
                ('prompt_template', models.TextField(help_text='Шаблон промпта с плейсхолдерами: {trend_title}, {trend_description}, {topic_name}, {tone}, {length}, {language}')),
                ('additional_instructions', models.TextField(blank=True, help_text="Дополнительные инструкции для AI (например, 'Всегда упоминай бренд X')")),
                ('is_default', models.BooleanField(default=False, help_text='Использовать этот шаблон по умолчанию для клиента')),
                ('include_hashtags', models.BooleanField(default=True, help_text='Генерировать хэштеги')),
                ('max_hashtags', models.IntegerField(default=5, help_text='Максимальное количество хэштегов')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_templates', to='core.client')),
            ],
            options={
                'verbose_name': 'Content Template',
                'verbose_name_plural': 'Content Templates',
                'ordering': ('-created_at',),
                'unique_together': {('client', 'name')},
            },
        ),
    ]
