# Generated by Django 5.2.8 on 2025-11-26 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contenttemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOKeywordSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает генерации'), ('generating', 'Генерируется'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='pending', max_length=20)),
                ('keywords_text', models.TextField(blank=True, help_text='Список ключевых SEO-фраз, сгенерированных AI')),
                ('ai_model', models.CharField(blank=True, help_text='Модель AI, использованная для генерации (например, gpt-4)', max_length=100)),
                ('prompt_used', models.TextField(blank=True, help_text='Промпт, использованный для генерации')),
                ('error_log', models.TextField(blank=True, help_text='Лог ошибок, если генерация не удалась')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo_keyword_sets', to='core.client')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo_keyword_sets', to='core.topic')),
            ],
            options={
                'verbose_name': 'SEO Keyword Set',
                'verbose_name_plural': 'SEO Keyword Sets',
                'ordering': ('-created_at',),
            },
        ),
    ]
