# Generated by Django 5.2.8 on 2025-11-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_seokeywordset'),
    ]

    operations = [
        migrations.AddField(
            model_name='seokeywordset',
            name='keyword_groups',
            field=models.JSONField(blank=True, default=dict, help_text='Группы SEO-фраз: commercial, general, informational и т.д.'),
        ),
        migrations.AlterField(
            model_name='seokeywordset',
            name='keywords_text',
            field=models.TextField(blank=True, help_text='[DEPRECATED] Список ключевых SEO-фраз, сгенерированных AI'),
        ),
    ]
