# Generated by Django 5.2.8 on 2025-11-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_seokeywordset_keyword_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='telegram_api_hash',
            field=models.CharField(blank=True, help_text='Telegram API Hash (получить на my.telegram.org)', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='telegram_api_id',
            field=models.CharField(blank=True, help_text='Telegram API ID (получить на my.telegram.org)', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='telegram_publish_channel',
            field=models.CharField(blank=True, help_text="Telegram канал для публикации постов (например, '@my_channel' или chat_id)", max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='telegram_source_channels',
            field=models.JSONField(blank=True, default=list, help_text="Список Telegram каналов для сбора контента (например, ['@rian_ru', '@tjournal'])"),
        ),
        migrations.AlterField(
            model_name='trenditem',
            name='source',
            field=models.CharField(choices=[('google_trends', 'Google Trends'), ('google_news_rss', 'Google News RSS'), ('telegram', 'Telegram'), ('youtube', 'YouTube'), ('rss_feed', 'RSS Feed'), ('news_api', 'News API'), ('manual', 'Manual')], max_length=30),
        ),
    ]
