# Generated by Django 5.2.8 on 2025-11-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_client_telegram_api_hash_client_telegram_api_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='telegram_source_channels',
            field=models.TextField(blank=True, default='@rian_ru, @tjournal', help_text='Список Telegram каналов для сбора контента через запятую (например: @rian_ru, @tjournal, @meduza)'),
        ),
    ]
