# Generated by Django 5.2.8 on 2025-11-27 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_client_telegram_source_channels'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='instagram_access_token',
            field=models.TextField(blank=True, help_text='Instagram Graph API токен доступа'),
        ),
        migrations.AddField(
            model_name='client',
            name='instagram_source_accounts',
            field=models.TextField(blank=True, help_text='Список Instagram аккаунтов для сбора контента через запятую (например: username1, username2)'),
        ),
        migrations.AddField(
            model_name='client',
            name='rss_source_feeds',
            field=models.TextField(blank=True, help_text='Список RSS/Atom фидов для сбора контента через запятую (например: https://lenta.ru/rss, https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml)'),
        ),
        migrations.AddField(
            model_name='client',
            name='youtube_api_key',
            field=models.CharField(blank=True, help_text='YouTube Data API v3 ключ (получить в Google Cloud Console)', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='youtube_source_channels',
            field=models.TextField(blank=True, help_text='Список YouTube каналов для сбора контента через запятую (например: UC_x5XG1OV2P6uZZ5FSM9Ttw, UCMCgOm8GZkHp8zJ6l0_fGxA или @channel_handle)'),
        ),
    ]
