# Generated by Django 5.2.8 on 2025-11-27 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_client_instagram_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='use_google_trends',
            field=models.BooleanField(default=True, help_text='Искать тренды в Google Trends', verbose_name='Google Trends'),
        ),
        migrations.AddField(
            model_name='topic',
            name='use_instagram',
            field=models.BooleanField(default=False, help_text='Искать в Instagram аккаунтах (требует access token и настройки аккаунтов)', verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='topic',
            name='use_rss',
            field=models.BooleanField(default=False, help_text='Искать в RSS фидах (требует настройки фидов в клиенте)', verbose_name='RSS'),
        ),
        migrations.AddField(
            model_name='topic',
            name='use_telegram',
            field=models.BooleanField(default=False, help_text='Искать в Telegram каналах (требует настройки каналов в клиенте)', verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='topic',
            name='use_youtube',
            field=models.BooleanField(default=False, help_text='Искать в YouTube каналах (требует API ключ и настройки каналов)', verbose_name='YouTube'),
        ),
        migrations.AlterField(
            model_name='trenditem',
            name='source',
            field=models.CharField(choices=[('google_trends', 'Google Trends'), ('google_news_rss', 'Google News RSS'), ('telegram', 'Telegram'), ('youtube', 'YouTube'), ('rss_feed', 'RSS Feed'), ('instagram', 'Instagram'), ('news_api', 'News API'), ('manual', 'Manual')], max_length=30),
        ),
    ]
