# Generated by Django 5.2.8 on 2025-11-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_topic_use_google_trends_topic_use_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='vkontakte_access_token',
            field=models.TextField(blank=True, help_text='VKontakte API токен доступа (получить на vk.com/dev)'),
        ),
        migrations.AddField(
            model_name='client',
            name='vkontakte_source_groups',
            field=models.TextField(blank=True, help_text='Список VK групп/пабликов для сбора контента через запятую (например: apiclub, thecode)'),
        ),
        migrations.AddField(
            model_name='topic',
            name='use_vkontakte',
            field=models.BooleanField(default=False, help_text='Искать в VK группах/пабликах (требует access token и настройки групп)', verbose_name='VKontakte'),
        ),
        migrations.AlterField(
            model_name='trenditem',
            name='source',
            field=models.CharField(choices=[('google_trends', 'Google Trends'), ('google_news_rss', 'Google News RSS'), ('telegram', 'Telegram'), ('youtube', 'YouTube'), ('rss_feed', 'RSS Feed'), ('instagram', 'Instagram'), ('vkontakte', 'VKontakte'), ('news_api', 'News API'), ('manual', 'Manual')], max_length=30),
        ),
    ]
