# Generated by Django 5.2.8 on 2025-11-28 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_client_vkontakte_access_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='telegram_publish_channel',
        ),
    ]
