# Generated by Django 5.2.8 on 2025-11-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_client_telegram_publish_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publish_image',
            field=models.BooleanField(default=True, help_text='Включать изображение в публикацию', verbose_name='Публиковать изображение'),
        ),
        migrations.AddField(
            model_name='post',
            name='publish_text',
            field=models.BooleanField(default=True, help_text='Включать текст в публикацию', verbose_name='Публиковать текст'),
        ),
        migrations.AddField(
            model_name='post',
            name='publish_video',
            field=models.BooleanField(default=True, help_text='Включать видео в публикацию', verbose_name='Публиковать видео'),
        ),
    ]
