# Generated by Django 5.2.8 on 2025-11-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_post_publish_image_post_publish_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='sale_for_who',
            field=models.TextField(blank=True, help_text="Целевая аудитория (например: 'начинающие разработчики 18-35 лет', 'родители детей 5-12 лет, жители Москвы')", verbose_name='Для кого'),
        ),
        migrations.AddField(
            model_name='client',
            name='sale_what',
            field=models.TextField(blank=True, help_text="Описание товаров/услуг клиента (например: 'онлайн-курсы по программированию', 'студия танцев для детей и взрослых')", verbose_name='Что продаем'),
        ),
    ]
