# Generated by Django 5.2.8 on 2025-11-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_client_sale_for_who_client_sale_what'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='sale_for_who',
        ),
        migrations.RemoveField(
            model_name='client',
            name='sale_what',
        ),
        migrations.AddField(
            model_name='client',
            name='avatar',
            field=models.TextField(blank=True, help_text="Портрет целевой аудитории (например: 'Мама двоих детей, работает удалённо, хочет больше времени для себя')", verbose_name='Аватар клиента'),
        ),
        migrations.AddField(
            model_name='client',
            name='desires',
            field=models.TextField(blank=True, help_text="Желания и цели аудитории (например: 'похудеть к лету, научиться танцевать, найти хобби, познакомиться с новыми людьми')", verbose_name='Хотелки'),
        ),
        migrations.AddField(
            model_name='client',
            name='objections',
            field=models.TextField(blank=True, help_text="Страхи и возражения аудитории (например: 'дорого, нет времени, боюсь выглядеть глупо, не получится')", verbose_name='Возражения/страхи'),
        ),
        migrations.AddField(
            model_name='client',
            name='pains',
            field=models.TextField(blank=True, help_text="Проблемы и боли целевой аудитории (например: 'нет времени на себя, стресс, лишний вес, низкая самооценка')", verbose_name='Боли'),
        ),
    ]
