# Generated by Django 5.2.8 on 2025-11-28

from django.db import migrations, models


def create_zavod_templates(apps, schema_editor):
    ContentTemplate = apps.get_model("core", "ContentTemplate")
    Client = apps.get_model("core", "Client")

    try:
        zavod_client = Client.objects.get(slug="zavod")
    except Client.DoesNotExist:
        return

    existing_names = set(
        ContentTemplate.objects.filter(client=zavod_client).values_list("name", flat=True)
    )

    base_additional_instructions = (
        "Всегда упоминай бренд в конце поста.\n"
        "Используй emoji умеренно (2-3 в тексте).\n"
        "Избегай сложных терминов."
    )

    # Продающий пост
    selling_name = "Продающий пост"
    if selling_name not in existing_names:
        ContentTemplate.objects.create(
            client=zavod_client,
            name=selling_name,
            type="selling",
            tone="friendly",
            length="long",
            language="ru",
            prompt_template="""
Ты — маркетолог проекта "zavod" и создаёшь контент для бизнеса по теме "{topic_name}".

ДАННЫЕ О ЦЕЛЕВОЙ АУДИТОРИИ:
Аватар: {avatar}
Боли: {pains}
Хотелки: {desires}
Возражения: {objections}

ЗАДАЧА:
Создай {length} {type} пост для социальных сетей в {tone} стиле на {language} языке.

НОВОСТЬ/ТРЕНД:
Заголовок: {trend_title}
Описание: {trend_description}

СТРУКТУРА ПОСТА:
1. Боль — опиши одну или две самые узнаваемые ситуации из жизни аватара, которые отражают его боли.
2. Хотелка — покажи, чего человек на самом деле хочет и к какой картинке результата стремится.
3. Почему не получалось — разберись в двух или трёх причинах и типичных ошибках, логично связав их с возражениями.
4. Как мы решаем — простыми словами объясни механику продукта или подхода "zavod" и чем он отличается.
5. Результат и доказательства — приведи один или два примера изменений, кейсов или ожидаемых результатов.
6. Призыв — сделай конкретный, но мягкий призыв к действию и сразу сними главное возражение.

ТРЕБОВАНИЯ К СТИЛЮ:
- Пиши человеческим разговорным языком, без воды и сложных терминов.
- Текст должен опираться на аватар, боли, хотелки и возражения.
- Структура должна ощущаться по абзацам, но без сухой нумерации внутри текста.
""".strip(),
            additional_instructions=base_additional_instructions,
            is_default=False,
            include_hashtags=True,
            max_hashtags=5,
        )

    # Триггерный пост
    trigger_name = "Триггерный пост"
    if trigger_name not in existing_names:
        ContentTemplate.objects.create(
            client=zavod_client,
            name=trigger_name,
            type="trigger",
            tone="friendly",
            length="medium",
            language="ru",
            prompt_template="""
Ты — маркетолог проекта "zavod" и создаёшь эмоциональный контент для темы "{topic_name}".

ДАННЫЕ О ЦЕЛЕВОЙ АУДИТОРИИ:
Аватар: {avatar}
Боли: {pains}
Хотелки: {desires}
Возражения: {objections}

ЗАДАЧА:
Создай {length} {type} пост для социальных сетей в {tone} стиле на {language} языке. Этот пост должен вызывать сильное узнавание и внутренний отклик, а не продавать в лоб.

НОВОСТЬ/ТРЕНД:
Заголовок: {trend_title}
Описание: {trend_description}

СТРУКТУРА ПОСТА:
1. Сильный крючок — одна короткая фраза, которая бьёт по главной боли или заблуждению и заставляет аватара сказать "это про меня".
2. История или наблюдение — короткая сценка из жизни аватара "вчера", где он действует привычным, но неэффективным образом.
3. Контраст — покажи разницу между "как было" и "как может быть", опираясь на хотелки.
4. Мини инсайт — сформулируй одну главную мысль или переосмысление, которое даёт читателю вспышку понимания.
5. Лёгкий намёк — аккуратно упомяни, что есть системный подход и работа с этим в "zavod", но без прямого оффера и жёсткого призыва.

ТРЕБОВАНИЯ К СТИЛЮ:
- Текст должен быть эмоциональным, но при этом понятным и конкретным.
- Фокус на чувствах, открытиях и узнаваемости, а не на описании продукта.
- В конце не делай прямых продаж, только мягкий намёк.
""".strip(),
            additional_instructions=base_additional_instructions,
            is_default=False,
            include_hashtags=True,
            max_hashtags=5,
        )

    # Экспертный пост
    expert_name = "Экспертный пост"
    if expert_name not in existing_names:
        ContentTemplate.objects.create(
            client=zavod_client,
            name=expert_name,
            type="expert",
            tone="professional",
            length="long",
            language="ru",
            prompt_template="""
Ты — эксперт и стратег по контенту проекта "zavod". Ты создаёшь структурный, полезный пост для темы "{topic_name}".

ДАННЫЕ О ЦЕЛЕВОЙ АУДИТОРИИ:
Аватар: {avatar}
Боли: {pains}
Хотелки: {desires}
Возражения: {objections}

ЗАДАЧА:
Создай {length} {type} пост для социальных сетей в {tone} стиле на {language} языке. Текст должен показывать глубину понимания темы и системное мышление.

НОВОСТЬ/ТРЕНД:
Заголовок: {trend_title}
Описание: {trend_description}

СТРУКТУРА ПОСТА:
1. Крючок — одна фраза, которая бьёт по боли или распространённому заблуждению аудитории.
2. Зачем это важно — объясни, как тема влияет на результаты, деньги, комфорт или безопасность аватара.
3. Диагностика — перечисли три-пять признаков, по которым читатель поймёт, что проблема есть у него.
4. Суть и экспертный разбор — разложи по полочкам два-четыре ключевых принципа, ошибки или механики, опираясь на боли и возражения.
5. Алгоритм, что делать — дай три-семь простых шагов, которые читатель может начать делать сам, двигаясь к своим хотелкам.
6. Мини вывод или инсайт — сделай короткое резюме, которое связывает системный подход с достижением желаемого результата.
7. Мягкий оффер — пригласи разобрать ситуацию или профиль в "zavod", без давления и агрессивных формулировок.

ТРЕБОВАНИЯ К СТИЛЮ:
- Пиши понятно и структурно, избегай излишнего теоретизирования.
- Каждый блок должен логично вытекать из предыдущего.
- Создавай ощущение, что автор точно понимает ситуацию читателя и ведёт его по шагам.
""".strip(),
            additional_instructions=base_additional_instructions,
            is_default=False,
            include_hashtags=True,
            max_hashtags=5,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_remove_client_sale_for_who_remove_client_sale_what_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contenttemplate",
            name="type",
            field=models.CharField(
                choices=[
                    ("selling", "Продающий"),
                    ("expert", "Экспертный"),
                    ("trigger", "Триггерный"),
                ],
                default="selling",
                help_text="Тип поста по структуре (продающий, экспертный, триггерный)",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="contenttemplate",
            name="prompt_template",
            field=models.TextField(
                help_text=(
                    "Шаблон промпта с плейсхолдерами: "
                    "{trend_title}, {trend_description}, {topic_name}, {tone}, {length}, {language}, "
                    "{type}, {avatar}, {pains}, {desires}, {objections}"
                )
            ),
        ),
        migrations.RunPython(create_zavod_templates, migrations.RunPython.noop),
    ]

