# Generated by Django 5.2.8 on 2025-11-30 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_contenttemplate_type_and_zavod_templates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='episode_number',
            field=models.IntegerField(blank=True, help_text='Номер эпизода в истории', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='regeneration_count',
            field=models.IntegerField(default=0, help_text='Количество регенераций текста'),
        ),
        migrations.AlterField(
            model_name='contenttemplate',
            name='type',
            field=models.CharField(choices=[('selling', 'Продающий'), ('expert', 'Экспертный'), ('trigger', 'Триггерный'), ('story', 'История (мини-сериал)')], default='selling', help_text='Тип поста по структуре (продающий, экспертный, триггерный)', max_length=20),
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Общий заголовок истории', max_length=500)),
                ('episodes', models.JSONField(default=list, help_text="Список эпизодов: [{'order': 1, 'title': '...'}, ...]")),
                ('episode_count', models.IntegerField(default=5, help_text='Количество эпизодов в истории')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('approved', 'Approved'), ('generating_posts', 'Generating Posts'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('generated_by', models.CharField(default='openrouter-chimera', help_text='Модель AI, использованная для генерации', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='core.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stories', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, help_text='Шаблон для генерации постов из эпизодов', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.contenttemplate')),
                ('trend_item', models.ForeignKey(blank=True, help_text='Тренд, на основе которого создана история', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='core.trenditem')),
            ],
            options={
                'verbose_name': 'Story',
                'verbose_name_plural': 'Stories',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='post',
            name='story',
            field=models.ForeignKey(blank=True, help_text='История, к которой относится этот пост', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.story'),
        ),
    ]
