# Generated by Django 5.2.8 on 2025-12-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_post_episode_number_post_regeneration_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenttemplate',
            name='tone',
            field=models.CharField(default='professional', help_text='Тон контента или свой кастомный тон', max_length=50),
        ),
        migrations.AlterField(
            model_name='contenttemplate',
            name='type',
            field=models.CharField(default='selling', help_text='Тип поста по структуре (продающий, экспертный, триггерный) или свой кастомный тип', max_length=50),
        ),
    ]
