# Generated by Django 5.2.8 on 2025-12-06 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_contenttemplate_tone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Техническое название (например: professional, friendly)', max_length=50)),
                ('label', models.CharField(help_text='Отображаемое название (например: Профессиональный, Дружественный)', max_length=100)),
                ('is_default', models.BooleanField(default=False, help_text='Предустановленный тон (создан автоматически)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_tones', to='core.client')),
            ],
            options={
                'verbose_name': 'Post Tone',
                'verbose_name_plural': 'Post Tones',
                'ordering': ['label'],
                'unique_together': {('client', 'value')},
            },
        ),
        migrations.CreateModel(
            name='PostType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Техническое название (например: selling, expert)', max_length=50)),
                ('label', models.CharField(help_text='Отображаемое название (например: Продающий, Экспертный)', max_length=100)),
                ('is_default', models.BooleanField(default=False, help_text='Предустановленный тип (создан автоматически)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_types', to='core.client')),
            ],
            options={
                'verbose_name': 'Post Type',
                'verbose_name_plural': 'Post Types',
                'ordering': ['label'],
                'unique_together': {('client', 'value')},
            },
        ),
    ]
