# Generated by Django 5.2.8 on 2025-12-06 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_posttone_posttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttone',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Оставьте пустым для системного тона, доступного всем клиентам', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_tones', to='core.client'),
        ),
        migrations.AlterField(
            model_name='posttype',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Оставьте пустым для системного типа, доступного всем клиентам', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_types', to='core.client'),
        ),
    ]
