# Generated by Django 5.2.8 on 2025-12-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_make_posttype_posttone_client_optional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenttemplate',
            name='prompt_template',
        ),
        migrations.AddField(
            model_name='contenttemplate',
            name='seo_prompt_template',
            field=models.TextField(default='', help_text='Шаблон промпта для генерации на основе SEO ключевых фраз. Плейсхолдеры: {seo_keywords}, {topic_name}, {tone}, {length}, {language}, {type}, {avatar}, {pains}, {desires}, {objections}', verbose_name='SEO промпт'),
        ),
        migrations.AddField(
            model_name='contenttemplate',
            name='trend_prompt_template',
            field=models.TextField(default='', help_text='Шаблон промпта для генерации на основе трендов. Плейсхолдеры: {trend_title}, {trend_description}, {trend_url}, {topic_name}, {tone}, {length}, {language}, {type}, {avatar}, {pains}, {desires}, {objections}', verbose_name='Trend промпт'),
        ),
    ]
