# Generated by Django 5.2.8 on 2025-12-06 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rename_prompt_to_seo_and_add_trend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seokeywordset',
            name='topic',
            field=models.ForeignKey(blank=True, help_text='(опционально) Историческая связь с конкретной темой', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seo_keyword_sets', to='core.topic'),
        ),
    ]
