# Generated by Django 5.2.8 on 2025-12-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_systemsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='seokeywordset',
            name='group_type',
            field=models.CharField(blank=True, choices=[('seo_pains', 'SEO Pains'), ('seo_desires', 'SEO Desires'), ('seo_objections', 'SEO Objections'), ('seo_avatar', 'SEO Avatar'), ('seo_keywords', 'SEO Keywords')], default='', help_text='Тип SEO-группы (по умолчанию пусто для старых записей)', max_length=32),
        ),
        migrations.AddField(
            model_name='seokeywordset',
            name='keywords_list',
            field=models.JSONField(blank=True, default=list, help_text='Список ключевых фраз для группы (используется для новых генераций)'),
        ),
    ]
