# Generated by Django 5.2.8 on 2025-12-06 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_seokeywordset_group_type_seokeywordset_keywords_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='telegram_client_channel',
            field=models.CharField(blank=True, help_text='Telegram канал клиента для публикации (например: @my_channel или -1001234567890)', max_length=255, verbose_name='Канал клиента'),
        ),
    ]
