# Generated by Django 5.2.8 on 2025-12-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_postimage_postvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='video_prompt_instructions',
            field=models.TextField(blank=True, help_text='Дополнительные пожелания к промптам для видео. Этот текст добавляется к базовым инструкциям при генерации видео.'),
        ),
    ]
