# Generated by Django 5.2.8 on 2025-12-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_systemsetting_video_prompt_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='image_generation_timeout',
            field=models.PositiveIntegerField(default=120, help_text='Таймаут (в секундах) для генерации и скачивания изображений. После его истечения запрос прерывается и пользователю возвращается ошибка о таймауте.'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='video_generation_timeout',
            field=models.PositiveIntegerField(default=600, help_text='Таймаут (в секундах) для генерации видео (включая ожидание ответа бота VEO/скачивание файлов). По истечении лимита процесс отменяется и появляется ошибка о таймауте.'),
        ),
    ]
