# Generated by Django 5.2.8 on 2025-12-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_systemsetting_image_generation_timeout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='fallback_ai_model',
            field=models.CharField(blank=True, default='tngtech/deepseek-r1t2-chimera:free', help_text='Запасная модель OpenRouter, используется если основная недоступна', max_length=255),
        ),
    ]
