# Generated by Django 5.2.8 on 2025-12-07 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_systemsetting_fallback_ai_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenttemplate',
            name='length',
            field=models.CharField(choices=[('short', 'Короткий (500-1000 символов)'), ('medium', 'Средний (1000-1500 символов)'), ('long', 'Длинный (1500-2000 символов)')], default='medium', help_text='Длина поста', max_length=20),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='postvideo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
