# Generated by Django 5.2.8 on 2025-12-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_update_length_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ai_analysis_channel_type',
            field=models.CharField(blank=True, help_text='Тип канала для анализа (например: telegram, instagram, youtube)', max_length=50, verbose_name='Тип канала'),
        ),
        migrations.AddField(
            model_name='client',
            name='ai_analysis_channel_url',
            field=models.CharField(blank=True, help_text='URL канала для AI анализа (например: https://t.me/example_channel)', max_length=255, verbose_name='AI Анализ канала'),
        ),
    ]
