# Generated by Django 5.2.8 on 2025-12-10 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_system_content_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Шаблон, использованный для генерации поста', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='core.contenttemplate'),
        ),
    ]
