# Generated by Django 5.2.8 on 2025-12-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_systemsetting_post_ai_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='image_generation_model',
            field=models.CharField(default='google/gemini-2.5-flash-image', help_text='Модель OpenRouter для генерации изображений (например, google/gemini-2.5-flash-image)', max_length=255),
        ),
    ]
