# Generated by Django 5.2.8 on 2025-12-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_socialaccount_timestamps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenttemplate',
            name='seo_prompt_template',
            field=models.TextField(default='', help_text='Шаблон промпта для генерации на основе SEO ключевых фраз. Плейсхолдеры: {seo_keywords}, {topic_name}, {tone}, {length}, {language}, {type}, {avatar}, {pains}, {desires}, {objections}, {books}', verbose_name='SEO промпт'),
        ),
    ]
