# Generated by Django 5.2.8 on 2025-12-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_contenttemplate_seo_prompt_template'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemsetting',
            old_name='image_generation_model',
            new_name='image_openrouter_model',
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='image_generation_method',
            field=models.CharField(choices=[('openrouter', 'OpenRouter API'), ('veo_photo', 'VEO фото (Telegram бот)'), ('giga_photo', 'Giga фото')], default='openrouter', help_text='Метод генерации изображений', max_length=50),
        ),
    ]
