# Generated by Django 5.2.8 on 2025-12-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_systemsetting_image_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsetting',
            name='image_openrouter_model',
            field=models.CharField(default='google/gemini-2.5-flash-image', help_text='Модель OpenRouter для генерации изображений (например, google/gemini-2.5-flash-image)', max_length=255, verbose_name='Image OpenRouter model'),
        ),
    ]
