# Generated by Django 5.2.8 on 2025-12-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_client_video_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='add_video_prompt',
            field=models.TextField(blank=True, help_text='Дополнительные инструкции для генерации видео (клиентские пожелания)', verbose_name='Additional video prompt'),
        ),
        migrations.AddField(
            model_name='client',
            name='base_video_prompt',
            field=models.TextField(blank=True, help_text='Базовые инструкции для AI генерации промпта видео (инструкции для режиссера)', verbose_name='Base video prompt'),
        ),
        migrations.AlterField(
            model_name='client',
            name='video_prompt',
            field=models.TextField(blank=True, help_text='Устаревшее поле. Используйте base_video_prompt и add_video_prompt', verbose_name='Video prompt (deprecated)'),
        ),
    ]
