# Generated by Django 5.2.8 on 2025-12-15 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_client_add_video_prompt_client_base_video_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='last_image_generation_at',
            field=models.DateTimeField(blank=True, help_text='Время запуска последней генерации изображения', null=True, verbose_name='Последняя генерация изображения'),
        ),
        migrations.AddField(
            model_name='client',
            name='last_video_generation_at',
            field=models.DateTimeField(blank=True, help_text='Время запуска последней генерации видео', null=True, verbose_name='Последняя генерация видео'),
        ),
    ]
