# Generated by Django 5.2.8 on 2025-12-15 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_client_last_image_generation_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hook_title',
            field=models.CharField(blank=True, help_text='Короткий привлекательный заголовок для привлечения внимания', max_length=100, verbose_name='Цепляющий заголовок'),
        ),
    ]
