# Generated by Django 5.2.8 on 2025-12-20 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_systemsetting_photo_prompt_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hook_title',
            field=models.CharField(blank=True, help_text='Короткий заголовок до 3 слов для нанесения на изображение', max_length=100, verbose_name='Цепляющий заголовок (для фото)'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='photo_prompt_instructions',
            field=models.TextField(blank=True, default='Use people with Slavic appearance, fair skin, any age, any gender', help_text='Дополнительные пожелания к промптам для генерации изображений. Этот текст добавляется к базовым инструкциям при генерации фото.'),
        ),
        migrations.CreateModel(
            name='WordstatQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_phrase', models.CharField(max_length=255)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('include_parent', models.BooleanField(default=False)),
                ('regions', models.JSONField(blank=True, default=list)),
                ('devices', models.JSONField(blank=True, default=list)),
                ('user_login', models.CharField(blank=True, max_length=255)),
                ('limit_per_second', models.PositiveIntegerField(blank=True, null=True)),
                ('daily_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('daily_limit_remaining', models.PositiveIntegerField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wordstat_queries', to='core.client')),
            ],
            options={
                'verbose_name': 'Wordstat Query',
                'verbose_name_plural': 'Wordstat Queries',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WordstatResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.TextField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('result_type', models.CharField(choices=[('top_request', 'Top request'), ('association', 'Association')], default='top_request', max_length=20)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.wordstatquery')),
            ],
            options={
                'verbose_name': 'Wordstat Result',
                'verbose_name_plural': 'Wordstat Results',
                'ordering': ('-count', 'phrase'),
            },
        ),
        migrations.AddIndex(
            model_name='wordstatquery',
            index=models.Index(fields=['client', 'created_at'], name='core_wordst_client__e432bf_idx'),
        ),
        migrations.AddIndex(
            model_name='wordstatquery',
            index=models.Index(fields=['client', 'request_phrase'], name='core_wordst_client__69e49e_idx'),
        ),
        migrations.AddIndex(
            model_name='wordstatresult',
            index=models.Index(fields=['query', 'result_type', 'count'], name='core_wordst_query_i_3276be_idx'),
        ),
    ]
