# Generated by Django 5.2.8 on 2025-02-15 00:00

from django.db import migrations, models


def migrate_length_to_numeric(apps, schema_editor):
    ContentTemplate = apps.get_model("core", "ContentTemplate")

    length_map = {
        "short": 800,
        "medium": 1200,
        "long": 1800,
    }
    default_length = 1200

    for template in ContentTemplate.objects.all().only("id", "length"):
        raw_value = template.length
        normalized = str(raw_value).strip().lower() if raw_value is not None else ""

        if normalized in length_map:
            new_value = length_map[normalized]
        else:
            try:
                new_value = int(normalized)
                if new_value <= 0:
                    new_value = default_length
            except (TypeError, ValueError):
                new_value = default_length

        if str(raw_value) != str(new_value):
            ContentTemplate.objects.filter(pk=template.pk).update(length=new_value)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_alter_schedule_social_account_nullable'),
    ]

    operations = [
        migrations.RunPython(migrate_length_to_numeric, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='contenttemplate',
            name='length',
            field=models.PositiveIntegerField(default=1200, help_text='Целевая длина поста в символах'),
        ),
    ]
