# Generated by Django 5.2.8 on 2025-12-22 08:43

from django.db import migrations, models


def fill_wordstat_fields(apps, schema_editor):
    WordstatQuery = apps.get_model("core", "WordstatQuery")
    for query in WordstatQuery.objects.all().only("id", "phrases", "request_phrase", "group_name"):
        phrases = query.phrases or []
        phrase_value = (query.request_phrase or "").strip()
        updated = False

        if not phrases and phrase_value:
            query.phrases = [phrase_value]
            updated = True

        if not (query.group_name or "").strip():
            query.group_name = phrase_value[:255]
            updated = True

        if updated:
            query.save(update_fields=["phrases", "group_name"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_contenttemplate_length_numeric'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # Колонка phrases уже могла быть создана ранее; обновляем только состояние миграций.
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='wordstatquery',
                    name='phrases',
                    field=models.JSONField(blank=True, default=list),
                ),
            ],
        ),
        migrations.AddField(
            model_name='wordstatquery',
            name='group_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.RunPython(fill_wordstat_fields, reverse_code=migrations.RunPython.noop),
    ]
