# Generated by Django 5.2.8 on 2025-12-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_wordstatresult_used_in_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='platform',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('telegram', 'Telegram'), ('youtube', 'YouTube'), ('vkontakte', 'VKontakte'), ('rss_zen', 'RSS Zen')], max_length=20),
        ),
    ]
