# Generated by Django 5.2.8 on 2025-12-25 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_alter_socialaccount_platform'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('instagram', 'Instagram'), ('youtube', 'YouTube'), ('telegram', 'Telegram'), ('vkontakte', 'VKontakte')], max_length=30)),
                ('name', models.CharField(blank=True, help_text='Человекочитаемое имя подключения', max_length=255)),
                ('provider_user_id', models.CharField(blank=True, help_text='ID пользователя у провайдера', max_length=255)),
                ('account_id', models.CharField(blank=True, help_text='ID аккаунта/канала для публикации', max_length=255)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('error', 'Error')], default='active', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_error', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='core.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
                'unique_together': {('client', 'provider', 'account_id')},
            },
        ),
        migrations.AddField(
            model_name='schedule',
            name='connection',
            field=models.ForeignKey(blank=True, help_text='Предпочтительное подключение для публикации', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='core.connection'),
        ),
        migrations.CreateModel(
            name='PostJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('instagram', 'Instagram'), ('youtube', 'YouTube'), ('telegram', 'Telegram'), ('vkontakte', 'VKontakte')], max_length=30)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('remote_id', models.CharField(blank=True, max_length=255)),
                ('remote_url', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_jobs', to='core.client')),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_jobs', to='core.connection')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_jobs', to='core.schedule')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
