# Generated by Django 5.2.8 on 2025-12-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_weekly_source_batch_and_reports'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER INDEX IF EXISTS core_weekly_source_idx RENAME TO core_weekly_client__84fb5e_idx;",
            reverse_sql="ALTER INDEX IF EXISTS core_weekly_client__84fb5e_idx RENAME TO core_weekly_source_idx;",
        ),
    ]
