# Generated by Django 5.2.8 on 2025-12-31 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0068_map_product_types_requirements"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="niche",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Например "пиццерия" или "школа психологии"',
                max_length=255,
                verbose_name="Ниша",
            ),
        ),
    ]

