# Generated by Django 5.2.8 on 2025-12-31 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0069_client_niche"),
    ]

    operations = [
        migrations.CreateModel(
            name="VeoVideoExport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("disk_path", models.CharField(max_length=1024, unique=True)),
                ("request_text", models.TextField(blank=True, help_text='Фрагмент ответа VEO: от "Ваш запрос:" до "🎛️ Инструмент:"')),
                ("telegram_message_id", models.BigIntegerField(blank=True, db_index=True, null=True)),
                ("telegram_message_date", models.DateTimeField(blank=True, null=True)),
                ("bot_username", models.CharField(blank=True, max_length=255)),
                ("source_url", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "VEO Video Export",
                "verbose_name_plural": "VEO Video Exports",
                "ordering": ("-created_at",),
            },
        ),
    ]

