# Generated by Django 5.2.8 on 2025-12-31 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0070_veo_video_export"),
    ]

    operations = [
        migrations.AlterField(
            model_name="veovideoexport",
            name="bot_username",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]

