# Generated by Django 5.2.8 on 2026-01-01 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0071_veo_video_export_bot_username_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebsiteScan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("base_url", models.CharField(help_text="Base website URL (e.g. https://example.com)", max_length=500)),
                ("task_id", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("progress", models.PositiveIntegerField(default=0)),
                ("max_depth", models.PositiveIntegerField(default=3)),
                ("max_pages", models.PositiveIntegerField(default=100)),
                ("robots_url", models.CharField(blank=True, max_length=700)),
                ("robots_txt", models.TextField(blank=True)),
                ("sitemap_urls", models.JSONField(blank=True, default=list)),
                ("mind_map_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="website_scans", to="core.client"),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="WebsiteScanPage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("url", models.CharField(max_length=700)),
                ("depth", models.PositiveIntegerField(default=0)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("content_type", models.CharField(blank=True, max_length=255)),
                ("title", models.TextField(blank=True)),
                ("meta_description", models.TextField(blank=True)),
                ("headings", models.JSONField(blank=True, default=dict)),
                ("wordstats", models.JSONField(blank=True, default=list)),
                ("can_fetch_all", models.BooleanField(default=True)),
                ("can_fetch_googlebot", models.BooleanField(default=True)),
                ("fetched_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="core.websitescanpage",
                    ),
                ),
                (
                    "scan",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="pages", to="core.websitescan"),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
        migrations.AddConstraint(
            model_name="websitescanpage",
            constraint=models.UniqueConstraint(fields=("scan", "url"), name="core_ws_unique_scan_url"),
        ),
        migrations.AddIndex(
            model_name="websitescan",
            index=models.Index(fields=["client", "status", "-created_at"], name="ws_client_status_created_idx"),
        ),
        migrations.AddIndex(
            model_name="websitescanpage",
            index=models.Index(fields=["scan", "depth"], name="core_ws_scan_depth_idx"),
        ),
        migrations.AddIndex(
            model_name="websitescanpage",
            index=models.Index(fields=["scan", "parent"], name="core_ws_scan_parent_idx"),
        ),
    ]

