# Generated by Django 5.2.8 on 2026-01-01 00:00

from django.db import migrations


ADD_TYPE_SQL = """
alter table if exists map.mind_maps
    add column if not exists type text not null default 'product';

update map.mind_maps set type = 'product' where type is null;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'chk_mind_maps_type'
    ) then
        alter table map.mind_maps
            add constraint chk_mind_maps_type check (type in ('product', 'website'));
    end if;
end;
$$;

create index if not exists idx_mind_maps_type on map.mind_maps(type);
"""


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0072_website_scans"),
    ]

    operations = [
        migrations.RunSQL(sql=ADD_TYPE_SQL, reverse_sql=""),
    ]

