# Generated by Django 5.2.8 on 2026-01-01 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0073_map_mind_maps_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebsiteScanPageContent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content_text", models.TextField(blank=True)),
                ("content_html", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "page",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content",
                        to="core.websitescanpage",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
    ]

