# Generated by Django 5.2.8 on 2026-01-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0074_website_scan_page_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="websitescan",
            name="pages_total",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]

