# Generated by Django 5.2.8 on 2026-01-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0075_website_scan_pages_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="websitescanpage",
            name="is_helper",
            field=models.BooleanField(default=False),
        ),
    ]

