# Generated by Django 5.2.8 on 2026-01-03 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_competitor_site_manual_flag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wordstat', models.CharField(help_text='Wordstat фраза / поисковый запрос', max_length=500)),
                ('options_why_now', models.JSONField(blank=True, default=list)),
                ('options_solution', models.JSONField(blank=True, default=list)),
                ('selected_why_now', models.JSONField(blank=True, default=list)),
                ('selected_solution', models.JSONField(blank=True, default=list)),
                ('outline_markdown', models.TextField(blank=True, help_text='Markdown-структура статьи без контента')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('options_ready', 'Options Ready'), ('outline_ready', 'Outline Ready'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='core.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ('-created_at',),
            },
        ),
    ]
