# Generated by Django 5.2.8 on 2026-01-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='lead_product_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='lead_product_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='article',
            name='tripwire_product_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='tripwire_product_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
