# Generated by Django 5.2.8 on 2026-01-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_article_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='seo_blocks',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
