# Generated by Django 5.2.8 on 2026-01-03 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_article_seo_blocks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('block_key', models.CharField(help_text='Системный ключ блока (например: Блок «Типичные ошибки»)', max_length=120)),
                ('subquery_h2', models.CharField(blank=True, max_length=300)),
                ('micro_intent', models.CharField(blank=True, max_length=300)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('content', models.TextField(blank=True, help_text='Сгенерированный текст блока (2–3 абзаца)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('blueprint_ready', 'Blueprint Ready'), ('ready', 'Ready'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('regeneration_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='core.article')),
            ],
            options={
                'verbose_name': 'Article Block',
                'verbose_name_plural': 'Article Blocks',
                'ordering': ('order', 'id'),
                'unique_together': {('article', 'block_key')},
            },
        ),
    ]
