# Generated by Django 5.2.8 on 2026-01-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_article_blocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='audience',
            field=models.TextField(blank=True, help_text='Целевая аудитория для промптов статьи'),
        ),
        migrations.AddField(
            model_name='articleblock',
            name='prompt_template',
            field=models.TextField(blank=True, help_text='Шаблон промпта для генерации блока'),
        ),
        migrations.AddField(
            model_name='articleblock',
            name='prompt_used',
            field=models.TextField(blank=True, help_text='Последний использованный промпт (рендер)'),
        ),
    ]
