# Generated by Django 5.2.8 on 2026-01-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0086_article_block_prompt_templates"),
    ]

    operations = [
        migrations.AddField(
            model_name="articleblock",
            name="prompt_is_custom",
            field=models.BooleanField(
                default=False,
                help_text="Если включено — использовать prompt_template вместо системного шаблона",
            ),
        ),
    ]

