# Generated by Django 5.2.8 on 2026-01-03

from django.db import migrations


def _cleanup_block_prompt_templates(apps, schema_editor):
    ArticleBlock = apps.get_model("core", "ArticleBlock")
    PromptTemplate = apps.get_model("core", "ArticleBlockPromptTemplate")

    system_map = {
        row.block_key: (row.prompt_template or "").strip()
        for row in PromptTemplate.objects.all().only("block_key", "prompt_template")
    }

    # До появления системных шаблонов prompt_template в ArticleBlock заполнялся дефолтным промптом.
    # Теперь prompt_template — это "корректировка", поэтому очищаем только те значения,
    # которые ровно совпадают с системным шаблоном.
    for block in ArticleBlock.objects.all().only("id", "block_key", "prompt_template"):
        current = (block.prompt_template or "").strip()
        if not current:
            continue
        system_value = system_map.get(block.block_key, "")
        if system_value and current == system_value:
            ArticleBlock.objects.filter(id=block.id).update(prompt_template="")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0087_article_block_custom_prompt_flag"),
    ]

    operations = [
        migrations.RunPython(_cleanup_block_prompt_templates, reverse_code=migrations.RunPython.noop),
    ]

