# Generated by Django 5.2.8 on 2026-01-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0088_article_block_prompt_template_cleanup"),
    ]

    operations = [
        migrations.RenameField(
            model_name="articleblock",
            old_name="subquery_h2",
            new_name="h2_title",
        ),
        migrations.AddField(
            model_name="articleblock",
            name="subquery",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="articleblock",
            name="key_points",
            field=models.TextField(blank=True),
        ),
    ]
