# Generated by Django 5.2.8 on 2026-01-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_article_status_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='project_instagram_channel',
            field=models.CharField(blank=True, help_text='Ссылка или @username Instagram аккаунта проекта', max_length=255, verbose_name='Instagram проекта'),
        ),
        migrations.AddField(
            model_name='client',
            name='project_telegram_channel',
            field=models.CharField(blank=True, help_text='Ссылка или @username Telegram канала проекта', max_length=255, verbose_name='Telegram проекта'),
        ),
        migrations.AddField(
            model_name='client',
            name='project_youtube_channel',
            field=models.CharField(blank=True, help_text='Ссылка или ID YouTube канала проекта', max_length=255, verbose_name='YouTube проекта'),
        ),
    ]
