# Generated by Django 5.2.8 on 2026-01-16 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_client_project_channels'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectChannelAnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_channel_runs', to='core.client')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProjectChannelPostStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_type', models.CharField(max_length=50)),
                ('channel_identifier', models.CharField(max_length=255)),
                ('external_id', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('reactions', models.PositiveIntegerField(default=0)),
                ('comments', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_channel_post_stats', to='core.client')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_stats', to='core.projectchannelanalysisrun')),
            ],
            options={
                'unique_together': {('run', 'channel_type', 'channel_identifier', 'external_id')},
            },
        ),
        migrations.AddIndex(
            model_name='projectchannelanalysisrun',
            index=models.Index(fields=['client', 'status', '-created_at'], name='pcr_client_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='projectchannelpoststat',
            index=models.Index(fields=['client', 'channel_type', 'channel_identifier', 'external_id'], name='pcps_client_channel_post_idx'),
        ),
        migrations.AddIndex(
            model_name='projectchannelpoststat',
            index=models.Index(fields=['run'], name='pcps_run_idx'),
        ),
    ]
