# Generated by Codex on 2026-01-23
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0114_weekly_sales_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordstatcluster',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
