# Generated by Codex on 2026-01-23
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0115_wordstat_cluster_is_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyContentStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(help_text='Дата начала недели (понедельник)')),
                ('comment', models.TextField(blank=True, default='')),
                ('wordstat_cluster_ids', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_content_strategies', to='core.client')),
            ],
            options={
                'verbose_name': 'Weekly Content Strategy',
                'verbose_name_plural': 'Weekly Content Strategies',
                'ordering': ('-week_start',),
            },
        ),
        migrations.AddConstraint(
            model_name='weeklycontentstrategy',
            constraint=models.UniqueConstraint(fields=('client', 'week_start'), name='core_weekly_content_strategy_client_week_unique'),
        ),
    ]
