# Generated by Django 5.2.8 on 2026-01-28 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_timestamps_to_client'),
        ('core', '0129_semantic_phrase_normalized_phrase'),
    ]

    operations = [
    ]
