# Generated by Django 5.2.8 on 2026-01-28 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_timestamps_to_client'),
        ('core', '0130_merge_20260128_2050'),
    ]

    operations = [
    ]
