# Generated by Django 5.2.8 on 2026-02-04

from django.db import migrations

ARTICLE_BLOCK_PROMPT_CODES = {
    "Вступление": "article_block_intro",
    "Блок «Почему проблема возникает»": "article_block_problem_causes",
    "Блок «Типичные ошибки»": "article_block_common_mistakes",
    "Блок «Правильная логика / система»": "article_block_correct_logic",
    "Блок «Пошаговая модель»": "article_block_step_model",
    "Блок «Пример / кейс / сценарий»": "article_block_case",
    "Блок «Что делать дальше»": "article_block_next_steps",
    "Мягкий переход к продукту:": "article_block_soft_product_transition",
    "Закрывающее утверждение": "article_block_closing_statement",
}


def _convert_placeholders(text: str) -> str:
    return (text or "").replace("{{", "${").replace("}}", "}")


def _seed_article_generator_prompts(apps, schema_editor):
    GeneratorPrompt = apps.get_model("core", "GeneratorPrompt")
    Template = apps.get_model("core", "ArticleBlockPromptTemplate")

    for block_key, code in ARTICLE_BLOCK_PROMPT_CODES.items():
        prompt_template = (
            Template.objects.filter(block_key=block_key)
            .values_list("prompt_template", flat=True)
            .first()
        )
        prompt_template = _convert_placeholders(prompt_template).strip()
        if not prompt_template:
            continue

        comment = f"Article block prompt: {block_key}"
        obj, created = GeneratorPrompt.objects.get_or_create(
            code=code,
            defaults={
                "prompt": prompt_template,
                "comment": comment,
                "group": "articles",
            },
        )
        if created:
            continue

        updates = {}
        if obj.group != "articles":
            updates["group"] = "articles"
        if obj.comment != comment:
            updates["comment"] = comment
        if not (obj.prompt or "").strip():
            updates["prompt"] = prompt_template

        if updates:
            for key, value in updates.items():
                setattr(obj, key, value)
            obj.save(update_fields=list(updates.keys()))


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0136_map_crm_categories"),
    ]

    operations = [
        migrations.RunPython(_seed_article_generator_prompts, reverse_code=migrations.RunPython.noop),
    ]
