# Generated by Django 5.2.8 on 2026-02-04

from django.db import migrations


OUTLINE_PROMPT = """
Сделай базовую структуру статьи по запросу: "$main_query".

Для каждого блока:
- придумай 1 H2 заголовок (4–10 слов)
- сформулируй 1 интент (кратко)
$extra_rules

Блоки (используй id):
$block_map

Верни строго JSON внутри тегов <answer>...</answer>:
<answer>
{
  "blocks": [
    {
      "id": 1,
      "h2_title": "<H2 заголовок>",
      "intent": "<интент>"
    }
  ]
}
</answer>

НЕ добавляй subquery и key_points. НЕ пиши пояснений и текста статьи.
"""


DETAILS_PROMPT = """
Заполни детали для блока $block_id ($block_name).
H2: "$h2_title"
Интент: "$intent"
$keyword_block

Сформулируй:
- 1 подзапрос (subquery)
- 3–6 ключевых смыслов (key_points)
$extra_rules

Верни строго JSON внутри тегов <answer>...</answer>:
<answer>
{
  "subquery": "<подзапрос>",
  "key_points": ["<смысл 1>", "<смысл 2>", "<смысл 3>"]
}
</answer>

НЕ добавляй другие поля. НЕ пиши пояснений.
"""


def _seed_blueprint_prompts(apps, schema_editor):
    GeneratorPrompt = apps.get_model("core", "GeneratorPrompt")
    prompts = [
        {
            "code": "article_blueprint_outline",
            "comment": "backend/core/tasks/articles.py: _build_outline_prompt",
            "prompt": OUTLINE_PROMPT,
        },
        {
            "code": "article_blueprint_details",
            "comment": "backend/core/tasks/articles.py: _build_details_prompt",
            "prompt": DETAILS_PROMPT,
        },
    ]
    for item in prompts:
        prompt_text = (item.get("prompt") or "").strip()
        obj, created = GeneratorPrompt.objects.get_or_create(
            code=item["code"],
            defaults={
                "prompt": prompt_text,
                "comment": item.get("comment", ""),
                "group": "articles",
            },
        )
        if created:
            continue
        updates = {}
        if obj.group != "articles":
            updates["group"] = "articles"
        if obj.comment != item.get("comment", ""):
            updates["comment"] = item.get("comment", "")
        if not (obj.prompt or "").strip():
            updates["prompt"] = prompt_text
        if updates:
            for key, value in updates.items():
                setattr(obj, key, value)
            obj.save(update_fields=list(updates.keys()))


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0137_article_prompts_to_generatorprompt"),
    ]

    operations = [
        migrations.RunPython(_seed_blueprint_prompts, reverse_code=migrations.RunPython.noop),
    ]
