# Generated by Django 5.2.8 on 2026-02-11 10:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0144_map_crm_payment_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('start_node_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'chains"."chains',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChainCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_type', models.CharField(max_length=30)),
                ('params', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chains"."chain_conditions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChainEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_port_id', models.CharField(blank=True, max_length=64, null=True)),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'chains"."chain_edges',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChainNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(default='text', max_length=20)),
                ('payload', models.JSONField(default=dict)),
                ('delay_seconds', models.IntegerField(default=0)),
                ('pos_x', models.FloatField(default=0)),
                ('pos_y', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'chains"."chain_nodes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChainSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('status', models.CharField(default='active', max_length=20)),
                ('context', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'chains"."chain_sessions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KbComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('block_id', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'map"."kb_comments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KbDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('icon', models.TextField(blank=True, null=True)),
                ('cover_image', models.TextField(blank=True, null=True)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('is_published', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_template', models.BooleanField(default=False)),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'map"."kb_documents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KbDocumentShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_token', models.TextField(unique=True)),
                ('permission', models.TextField(default='view')),
                ('password', models.TextField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('visit_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'map"."kb_shares',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KbDocumentTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'map"."kb_document_tags',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KbDocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version_number', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'map"."kb_document_versions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KbFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'map"."kb_folders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KbTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('color', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'map"."kb_tags',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MindEdge',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.TextField(default='default')),
                ('label', models.TextField(blank=True, null=True)),
                ('meta', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'map"."mind_edges',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MindMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.TextField(default='product')),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'map"."mind_maps',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MindMapMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField()),
            ],
            options={
                'db_table': 'map"."mind_map_members',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MindNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('color', models.TextField(blank=True, null=True)),
                ('shape', models.TextField(blank=True, null=True)),
                ('meta', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'map"."mind_nodes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MindNodeProperty',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('value', models.TextField()),
                ('delta', models.TextField(blank=True, null=True)),
                ('order_index', models.IntegerField(default=0)),
                ('meta', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'map"."mind_node_properties',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('value', models.TextField(blank=True, null=True)),
                ('goal', models.TextField(blank=True, null=True)),
                ('requirements_name', models.TextField(blank=True, null=True)),
                ('requirements_packages', models.TextField(blank=True, null=True)),
                ('requirements_audience', models.TextField(blank=True, null=True)),
                ('requirements_transformation', models.TextField(blank=True, null=True)),
                ('requirements_metrics', models.TextField(blank=True, null=True)),
                ('requirements_method', models.TextField(blank=True, null=True)),
                ('requirements_lesson_format', models.TextField(blank=True, null=True)),
                ('requirements_program_modules', models.TextField(blank=True, null=True)),
                ('requirements_packaging', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'map"."product_types',
                'ordering': ('-updated_at',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TelegramTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_name', models.TextField()),
                ('telegram_user_id', models.BigIntegerField()),
                ('telegram_message_id', models.BigIntegerField(blank=True, null=True)),
                ('message_text', models.TextField()),
                ('received_at', models.DateTimeField()),
                ('rating', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'map"."crm_level',
                'ordering': ('-received_at', '-id'),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserTenantBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_chat_id', models.BigIntegerField()),
                ('contact_id', models.IntegerField(blank=True, null=True)),
                ('bound_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'map"."user_tenant_binding',
                'ordering': ('-bound_at', '-id'),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(help_text='HEX цвет для UI', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'crm_client_categories',
            },
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('duration_minutes', models.IntegerField(default=60)),
                ('color', models.CharField(help_text='HEX цвет для UI', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'crm_event_types',
            },
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
            ],
            options={
                'verbose_name': 'Промпт статьи',
                'verbose_name_plural': 'Промпты статей',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.articleblockprompttemplate',),
        ),
        migrations.AlterModelOptions(
            name='articleblockprompttemplate',
            options={'ordering': ('block_key',), 'verbose_name': 'Промпт блока статьи', 'verbose_name_plural': 'Промпты блоков статьи'},
        ),
        migrations.AlterModelOptions(
            name='clientproduct',
            options={'managed': False, 'ordering': ('-updated_at',)},
        ),
        migrations.RemoveField(
            model_name='client',
            name='created_at',
        ),
        migrations.AddField(
            model_name='client',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID клиента'),
        ),
        migrations.AddField(
            model_name='client',
            name='yookassa_connected',
            field=models.BooleanField(default=False, help_text='True если клиент успешно подключил свой YooKassa-магазин', verbose_name='YooKassa подключена'),
        ),
        migrations.AddField(
            model_name='client',
            name='yookassa_oauth_token',
            field=models.CharField(blank=True, help_text='Заполняется автоматически при подключении через OAuth', max_length=1000, null=True, verbose_name='YooKassa OAuth-токен'),
        ),
        migrations.AddField(
            model_name='client',
            name='yookassa_return_url',
            field=models.CharField(blank=True, help_text='Если пусто — генерируется автоматически как /payments/return/<uuid>/', max_length=500, null=True, verbose_name='YooKassa Return URL'),
        ),
        migrations.AddField(
            model_name='client',
            name='yookassa_secret_key',
            field=models.CharField(blank=True, help_text='Секретный ключ из личного кабинета YooKassa', max_length=500, null=True, verbose_name='YooKassa Secret Key'),
        ),
        migrations.AddField(
            model_name='client',
            name='yookassa_shop_id',
            field=models.CharField(blank=True, help_text='ID магазина из личного кабинета YooKassa', max_length=100, null=True, verbose_name='YooKassa Shop ID'),
        ),
        migrations.AlterField(
            model_name='articleblock',
            name='prompt_is_custom',
            field=models.BooleanField(default=False, help_text='DEPRECATED: больше не используется (оставлено для совместимости).'),
        ),
        migrations.AlterField(
            model_name='articleblock',
            name='prompt_template',
            field=models.TextField(blank=True, help_text='Корректировка (добавляется к системному промпту блока)'),
        ),
        migrations.AlterField(
            model_name='generationevent',
            name='event_type',
            field=models.CharField(choices=[('post', 'Post generation'), ('article_write', 'Article write'), ('article_evaluate', 'Article evaluate'), ('channel_analysis', 'Channel analysis'), ('website_analysis', 'Website analysis'), ('weekly_collection', 'Weekly collections'), ('seo_group', 'SEO groups'), ('semantic_clusters', 'Semantic clusters'), ('semantic_phrases', 'Semantic phrases'), ('wordstat_query', 'Wordstat query'), ('google_query', 'Google query'), ('product', 'Product generation'), ('product_map', 'Product map'), ('book_search', 'Book search'), ('book_semantics', 'Book semantics')], max_length=32),
        ),
        migrations.AlterField(
            model_name='semanticphrase',
            name='type',
            field=models.CharField(choices=[('key', 'Key'), ('lsi', 'LSI'), ('wordstat', 'Wordstat'), ('association', 'Association')], default='key', max_length=20),
        ),
        migrations.CreateModel(
            name='MindNodePosition',
            fields=[
                ('node', models.OneToOneField(db_column='node_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='position', serialize=False, to='core.mindnode')),
                ('layout_name', models.TextField(default='default')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'map"."mind_node_positions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CRMClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('active', 'Активный'), ('inactive', 'Неактивный'), ('archived', 'В архиве')], default='active', max_length=20)),
                ('photo_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.clientcategory')),
                ('zavod_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.client')),
            ],
            options={
                'db_table': 'crm_clients',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField()),
                ('is_important', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.crmclient')),
            ],
            options={
                'db_table': 'crm_notes',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('scheduled', 'Запланировано'), ('completed', 'Завершено'), ('cancelled', 'Отменено'), ('no_show', 'Не явился')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.crmclient')),
                ('event_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.eventtype')),
            ],
            options={
                'db_table': 'crm_events',
                'constraints': [models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='check_event_time')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Сумма платежа', max_digits=10)),
                ('currency', models.CharField(choices=[('RUB', 'Рубль'), ('USD', 'Доллар'), ('EUR', 'Евро')], default='RUB', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('paid', 'Оплачено'), ('failed', 'Ошибка'), ('refunded', 'Возврат')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.crmclient')),
            ],
            options={
                'db_table': 'crm_payments',
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='check_positive_amount')],
            },
        ),
        migrations.CreateModel(
            name='YooKassaPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='ID платежа в YooKassa')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('succeeded', 'Оплачен'), ('canceled', 'Отменён'), ('waiting_for_capture', 'Ожидает подтверждения')], default='pending', max_length=50, verbose_name='Статус')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма')),
                ('plan_code', models.CharField(blank=True, help_text='Код тарифа, за который производится оплата', max_length=100, verbose_name='Код тарифа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yookassa_payments', to='core.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'YooKassa Платёж',
                'verbose_name_plural': 'YooKassa Платежи',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['payment_id'], name='yk_payment_id_idx'), models.Index(fields=['client', '-created_at'], name='yk_client_created_idx')],
            },
        ),
    ]
