# Generated by Django 5.2 on 2026-03-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0190_drop_product_course_lessons_video_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="custom_domain",
            field=models.CharField(
                blank=True,
                help_text="Свой домен клиента (например, site.example.com)",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="domain_verified",
            field=models.BooleanField(
                default=False,
                help_text="Домен подтвержден через DNS-проверку",
            ),
        ),
    ]
