# Generated by Django 5.2 on 2026-03-11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0191_client_custom_domain"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectTeamInvite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider", models.CharField(choices=[("telegram", "Telegram"), ("vk", "VK")], max_length=32)),
                ("account_handle_raw", models.CharField(max_length=255)),
                ("account_handle_normalized", models.CharField(max_length=255)),
                ("role", models.CharField(choices=[("editor", "Editor")], default="editor", max_length=20)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("accepted", "Accepted"), ("revoked", "Revoked")], default="pending", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("accepted_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="accepted_team_invites", to=settings.AUTH_USER_MODEL)),
                ("client", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="team_invites", to="core.client")),
                ("invited_by", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="created_team_invites", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="UserActiveClientPreference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("client", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="active_user_preferences", to="core.client")),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="active_client_preference", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name="projectteaminvite",
            index=models.Index(fields=["provider", "account_handle_normalized"], name="idx_team_invite_prov_handle"),
        ),
        migrations.AddIndex(
            model_name="projectteaminvite",
            index=models.Index(fields=["client", "status"], name="idx_team_invite_client_status"),
        ),
        migrations.AddConstraint(
            model_name="projectteaminvite",
            constraint=models.UniqueConstraint(
                condition=Q(status="pending"),
                fields=("client", "provider", "account_handle_normalized"),
                name="uniq_team_invite_pending_handle",
            ),
        ),
    ]
