# Generated by Django 5.2 on 2026-03-23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0192_project_team_invites"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactCoachingProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("contact_id", models.IntegerField(db_index=True)),
                ("intention", models.TextField(blank=True, default="")),
                ("wheel", models.JSONField(blank=True, default=list)),
                ("competencies", models.JSONField(blank=True, default=list)),
                ("goals", models.JSONField(blank=True, default=list)),
                ("milestones", models.JSONField(blank=True, default=list)),
                ("sessions", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="contact_coaching_profiles", to="core.client")),
            ],
            options={
                "ordering": ("tenant_id", "contact_id", "id"),
            },
        ),
        migrations.AddConstraint(
            model_name="contactcoachingprofile",
            constraint=models.UniqueConstraint(fields=("tenant", "contact_id"), name="uniq_contact_coaching_profile"),
        ),
        migrations.AddIndex(
            model_name="contactcoachingprofile",
            index=models.Index(fields=["tenant", "contact_id"], name="idx_contact_coaching_profile"),
        ),
    ]
