# Generated by Django 5.2 on 2026-03-30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0199_crm_tasks_coaching_metadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoachingGoal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.CharField(max_length=128)),
                ("goal_type", models.CharField(choices=[("personal", "Personal"), ("group", "Group")], default="personal", max_length=16)),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("progress", models.PositiveSmallIntegerField(default=0)),
                ("horizon", models.CharField(choices=[("year", "Year"), ("quarter", "Quarter"), ("month", "Month")], default="quarter", max_length=16)),
                ("status", models.CharField(choices=[("active", "Active"), ("paused", "Paused"), ("achieved", "Achieved"), ("revised", "Revised")], default="active", max_length=16)),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("group", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="coaching_goals", to="core.coachgroup")),
                ("profile", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="goal_rows", to="core.contactcoachingprofile")),
            ],
            options={
                "ordering": ("sort_order", "created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="CoachingGoalCompetency",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("competency_id", models.CharField(max_length=128)),
                ("competency_name", models.CharField(blank=True, default="", max_length=255)),
                ("weight", models.FloatField(default=0)),
                ("sort_order", models.IntegerField(default=0)),
                ("goal", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="competency_links", to="core.coachinggoal")),
            ],
            options={
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.AddConstraint(
            model_name="coachinggoal",
            constraint=models.UniqueConstraint(fields=("profile", "public_id"), name="uniq_coaching_goal_profile_public_id"),
        ),
        migrations.AddIndex(
            model_name="coachinggoal",
            index=models.Index(fields=["profile", "sort_order", "id"], name="idx_coach_goal_profile_sort"),
        ),
        migrations.AddIndex(
            model_name="coachinggoal",
            index=models.Index(fields=["profile", "goal_type"], name="idx_coach_goal_profile_type"),
        ),
        migrations.AddIndex(
            model_name="coachinggoal",
            index=models.Index(fields=["group"], name="idx_coach_goal_group"),
        ),
        migrations.AddIndex(
            model_name="coachinggoalcompetency",
            index=models.Index(fields=["goal", "sort_order", "id"], name="idx_coach_goal_comp_goal_sort"),
        ),
    ]
